// SPDX-License-Identifier: LicenseRef-probectl-TBD
// Code generated by cmd/probectl-sdkgen from internal/control/openapi.json; DO NOT EDIT.

/* eslint-disable */

export type JsonValue = string | number | boolean | null | JsonObject | JsonValue[]
export interface JsonObject { [key: string]: JsonValue }

export interface ABACPolicy {
  effect: "allow" | "deny"
  enabled?: boolean
  id?: string
  name?: string
  permission: string
  priority?: number
  resource?: { [key: string]: string }
  subject?: { [key: string]: string }
}

export interface ABACPolicyList {
  items?: ABACPolicy[]
}

export interface AIAnswer {
  confidence?: "low" | "medium" | "high"
  degraded?: boolean
  evidence?: AIEvidence[]
  findings?: AIFinding[]
  id?: string
  insufficient_evidence?: boolean
  model?: string
  question?: string
  root_cause?: string
  root_cause_citations?: AICitation[]
  root_cause_grounded?: boolean
  tenant?: string
}

export interface AIAskRequest {
  question: string
  subject?: { [key: string]: string }
}

export interface AICitation {
  evidence_id?: string
}

export interface AIEvidence {
  domain?: string
  id?: string
  occurred_at?: string
  plane?: string
  ref?: string
  severity?: string
  summary?: string
  title?: string
}

export interface AIFeedbackRequest {
  answer_id: string
  comment?: string
  question?: string
  rating: "up" | "down"
}

export interface AIFinding {
  citations?: AICitation[]
  statement?: string
}

export interface Agent {
  agent_version?: string
  capabilities: string[]
  created_at?: string
  hostname?: string
  id: string
  last_seen_at?: string
  name: string
  registered_at?: string
  spiffe_id?: string
  status: "registered" | "online" | "offline"
  tenant_id: string
}

export interface AgentList {
  items: Agent[]
  next_cursor?: string
}

export interface AgentPatch {
  name: string
}

export interface AlertChannelTestRequest {
  channel: ChannelSpec
  metric?: string
  rule_name?: string
}

export interface AlertChannelTestResponse {
  accepted: boolean
  type: "webhook" | "email"
}

export interface AlertList {
  items?: AlertRule[]
}

export interface AlertRequest {
  channels?: ChannelSpec[]
  comparison?: "gt" | "lt" | "gte" | "lte" | "eq" | "neq"
  enabled?: boolean
  for_n?: number
  match?: { [key: string]: string }
  metric: string
  name: string
  renotify_seconds?: number
  sensitivity?: number
  severity?: "info" | "warning" | "critical"
  threshold?: number
  type: "threshold" | "baseline"
  window?: number
}

export interface AlertRule {
  channels?: ChannelSpec[]
  comparison?: string
  created_at?: string
  enabled?: boolean
  for_n?: number
  id?: string
  match?: { [key: string]: string }
  metric?: string
  name?: string
  renotify_seconds?: number
  sensitivity?: number
  severity?: string
  tenant_id?: string
  threshold?: number
  type?: "threshold" | "baseline"
  updated_at?: string
  window?: number
}

export interface AnomalyCitation {
  metric?: string
  plane?: string
  ref?: string
  source?: string
}

export interface AnomalyTrainingWindow {
  end?: string
  samples?: number
  start?: string
}

export interface AuditEvent {
  action: string
  actor: string
  created_at?: string
  data?: JsonObject
  hash: string
  prev_hash?: string
  seq: number
  target?: string
}

export interface AuditList {
  items: AuditEvent[]
  next: number
}

export interface AuditVerify {
  detail?: string
  ok: boolean
}

export interface AuthorRequest {
  prompt: string
}

export interface BGPEvent {
  attributes?: { [key: string]: string }
  id?: string
  incident_id?: string
  kind?: string
  occurred_at?: string
  prefix?: string
  severity?: string
  summary?: string
  target?: string
  title?: string
}

export interface BGPEventList {
  bgp_running?: boolean
  effective_limit?: number
  items?: BGPEvent[]
}

export interface ChangeCandidate {
  event?: ChangeEvent
  reason?: string
  score?: number
}

export interface ChangeCandidateList {
  items?: ChangeCandidate[]
}

export interface ChangeEvent {
  actor?: string
  id?: string
  kind?: string
  occurred_at?: string
  prefix?: string
  ref?: string
  source?: string
  summary?: string
  target?: string
  title?: string
  url?: string
}

export interface ChangeEventList {
  items?: ChangeEvent[]
}

export interface ChannelSpec {
  recipients?: string[]
  secret?: string
  type: "webhook" | "email"
  url?: string
}

export interface CollectorConfigHint {
  env: { [key: string]: string }
  yaml: { [key: string]: string }
}

export interface CollectorRegisterRequest {
  hostname?: string
  plane: "flow" | "device" | "ebpf" | "endpoint"
  token: string
}

export interface CollectorRegistration {
  agent_id: string
  capabilities: string[]
  config: CollectorConfigHint
  hostname?: string
  plane: "flow" | "device" | "ebpf" | "endpoint"
  tenant_id: string
}

export interface DeviceInventory {
  address?: string
  first_seen?: string
  id?: string
  labels?: { [key: string]: string }
  last_seen?: string
  name?: string
}

export interface DeviceInventoryList {
  at?: string
  effective_limit?: number
  items?: DeviceInventory[]
  topology_running?: boolean
}

export interface DeviceMetricSummary {
  agent_id?: string
  device?: string
  device_name?: string
  id?: string
  if_index?: string
  if_name?: string
  last_seen?: string
  metric?: string
  name?: string
  source?: string
  summary?: string
  value?: number
}

export interface DeviceMetricSummaryList {
  effective_limit?: number
  items?: DeviceMetricSummary[]
  metrics_running?: boolean
}

export interface DiscoverProposal {
  rationale?: string
  score?: number
  source?: string
  spec?: TestSpec
}

export interface DiscoverProposalList {
  proposals?: DiscoverProposal[]
}

export interface EBPFServiceEdge {
  agent_id?: string
  bytes?: number
  connections?: number
  destination?: string
  destination_port?: number
  id?: string
  l7_protocol?: string
  name?: string
  packets?: number
  source?: string
  summary?: string
  window_start?: string
}

export interface EBPFServiceMap {
  ebpf_running?: boolean
  effective_limit?: number
  items?: EBPFServiceEdge[]
  source?: string
}

export interface Error {
  error: ErrorDetail
}

export type ErrorCode = "internal" | "bad_request" | "validation" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "unavailable" | "rate_limited" | "too_large" | "writer_unavailable" | "quota_exceeded" | "tenant_suspended" | "tenant_offboarded" | "approvals_disabled" | "blast_radius_exceeded" | "blast_radius_unknown" | "not_proposed"

export interface ErrorDetail {
  code: ErrorCode
  message: string
  request_id?: string
}

export interface FlowAnomaly {
  baseline_bps?: number
  current_bps?: number
  exporter?: string
  feature_citations?: AnomalyCitation[]
  features?: { [key: string]: number }
  iface?: number
  model?: string
  sigma?: number
  stddev_bps?: number
  training_window?: AnomalyTrainingWindow
  ts?: string
}

export interface FlowAnomalyList {
  items?: FlowAnomaly[]
}

export interface FlowCapacityList {
  items?: FlowCapacityPoint[]
}

export interface FlowCapacityPoint {
  bps?: number
  exporter?: string
  iface?: number
  pps?: number
  ts?: string
}

export interface FlowTopList {
  effective_limit?: number
  items?: FlowTopRow[]
  window?: string
}

export interface FlowTopRow {
  bytes?: number
  detail?: string
  flows?: number
  key?: string
  packets?: number
}

export interface Health {
  status: string
}

export interface Hierarchy {
  items: HierarchyOrganization[]
}

export interface HierarchyCreate {
  name: string
  slug: string
}

export interface HierarchyOrganization {
  created_at: string
  id: string
  name: string
  slug: string
  teams: HierarchyTeam[]
  tenant_id: string
  updated_at: string
}

export interface HierarchyOrganizationFlat {
  created_at: string
  id: string
  name: string
  slug: string
  tenant_id: string
  updated_at: string
}

export interface HierarchyProject {
  created_at: string
  id: string
  name: string
  slug: string
  team_id: string
  tenant_id: string
  updated_at: string
}

export interface HierarchyTeam {
  created_at: string
  id: string
  name: string
  org_id: string
  projects: HierarchyProject[]
  slug: string
  tenant_id: string
  updated_at: string
}

export interface HierarchyTeamFlat {
  created_at: string
  id: string
  name: string
  org_id: string
  slug: string
  tenant_id: string
  updated_at: string
}

export interface Hop {
  nodes: HopNode[]
  ttl: number
}

export interface HopNode {
  ip: string
  loss_ratio?: number
  mpls?: MPLSLabel[]
  received?: number
  rtt_avg_ms?: number
  rtt_max_ms?: number
  rtt_min_ms?: number
  sent?: number
}

export interface Incident {
  id?: string
  last_seen_at?: string
  prefix?: string
  resolved_at?: string
  severity?: "info" | "warning" | "critical"
  signal_count?: number
  signals?: Signal[]
  started_at?: string
  status?: "open" | "resolved"
  target?: string
  tenant_id?: string
  title?: string
}

export interface IncidentList {
  items?: Incident[]
}

export interface IncidentPatch {
  status: "resolved"
}

export interface InventorySavedView {
  created_at: string
  filters: { [key: string]: string }
  id: string
  name: string
  owner_id: string
  surface: "endpoints" | "targets" | "agents" | "incidents" | "alerts"
  tenant_id: string
  updated_at: string
}

export interface InventorySavedViewInput {
  filters?: { [key: string]: string }
  name: string
  surface: "endpoints" | "targets" | "agents" | "incidents" | "alerts"
}

export interface InventorySavedViewList {
  items: InventorySavedView[]
}

export interface IsolationLaneStatus {
  mode: "shared_tenant_tagged" | "tenant_namespaced" | "invalid"
  namespace?: string
  strict: boolean
  tenant_tagged: boolean
  topic_example: string
}

export interface IsolationRLSStatus {
  database_configured: boolean
  detail: string
  enforced: boolean
  healthy: boolean
}

export interface IsolationRoutingStatus {
  clickhouse_database?: string
  clickhouse_residency_plane_configured: boolean
  enabled: boolean
  error?: string
  fail_closed: boolean
  object_prefix?: string
  pg_schema?: string
  resolved: boolean
}

export interface IsolationStatus {
  effective_model: "pooled" | "siloed" | "hybrid"
  id: string
  lane_namespace: IsolationLaneStatus
  name: string
  registry_model: string
  residency?: string
  rls: IsolationRLSStatus
  silo_routing: IsolationRoutingStatus
  status: "healthy" | "degraded" | "unknown"
  summary: string
  tenant_id: string
}

export interface LifecycleRetentionInput {
  flow_retention_days: number | null
}

export interface LifecycleStatus {
  flow_retention_days: number | null
  isolation_model: string
  residency?: string
  tenant_id?: string
  updated_by?: string
}

export interface Link {
  from?: string
  to?: string
  ttl?: number
}

export interface MPLSLabel {
  label?: number
  s?: boolean
  tc?: number
  ttl?: number
}

export interface Me {
  display_name?: string
  email?: string
  locale?: string
  mfa_satisfied?: boolean
  permissions: string[]
  tenant_id: string
  tenant_locale?: string
  tenant_time_zone?: string
  time_zone?: string
  user_id: string
}

export interface OncallStatus {
  configured: boolean
  dispatcher_running: boolean
  id: string
  inbound: JsonObject[]
  inbound_configured: boolean
  inbound_webhook_count: number
  name: string
  outbound: JsonObject[]
  outbound_configured: boolean
  outbound_connector_count: number
  providers: JsonObject[]
  secrets_redacted: boolean
  summary: string
  supported_providers: "pagerduty" | "opsgenie" | "slack" | "teams" | "servicenow" | "jira"[]
  tls_required: boolean
}

export interface OncallTestRequest {
  connector_id: string
}

export interface OncallTestResponse {
  accepted: boolean
  connector_id: string
  external_ref?: string
  provider: string
  status?: string
}

export interface Path {
  destination_reached?: boolean
  hops: Hop[]
  links: Link[]
  max_hops?: number
  mode: string
  target: string
  target_ip?: string
  trace_count?: number
}

export interface SCIMToken {
  created_at: string
  id: string
  last_used_at?: string
  name: string
  revoked_at?: string
  tenant_id: string
}

export interface SCIMTokenCreate {
  name?: string
}

export interface SCIMTokenCreated {
  id: string
  name: string
  token: string
}

export interface SCIMTokenList {
  items?: SCIMToken[]
}

export interface SIEMStatus {
  audit_poll_interval: string
  buffer_size: number
  configured: boolean
  enabled: boolean
  endpoint_configured: boolean
  endpoint_host?: string
  endpoint_tls_configured: boolean
  format: string
  id: string
  name: string
  no_drop_delivery: boolean
  preset: "generic" | "splunk" | "sentinel" | "elastic" | "chronicle"
  reason?: "disabled" | "missing_endpoint" | "insecure_endpoint" | "invalid_format" | "configured"
  redact_key_count: number
  siem_running: boolean
  streams: "audit" | "threat"[]
  summary: string
  tls_required: boolean
  token_configured: boolean
}

export interface Signal {
  attributes?: { [key: string]: string }
  kind?: string
  occurred_at?: string
  plane?: string
  prefix?: string
  severity?: "info" | "warning" | "critical"
  summary?: string
  target?: string
  title?: string
}

export interface Test {
  created_at: string
  enabled?: boolean
  id: string
  interval_seconds?: number
  name: string
  params?: { [key: string]: string }
  target?: string
  tenant_id: string
  timeout_seconds?: number
  type: "icmp" | "tcp" | "udp" | "dns" | "http" | "browser" | "a2a" | "noop" | "voice"
  updated_at: string
}

export interface TestList {
  items: Test[]
  next_cursor?: string
}

export interface TestProposal {
  rationale?: string
  source?: string
  spec?: TestSpec
}

export interface TestRequest {
  enabled?: boolean
  interval_seconds?: number
  name: string
  params?: { [key: string]: string }
  target?: string
  timeout_seconds?: number
  type: "icmp" | "tcp" | "udp" | "dns" | "http" | "browser" | "a2a" | "noop" | "voice"
}

export interface TestSpec {
  enabled?: boolean
  interval_seconds?: number
  name?: string
  params?: { [key: string]: string }
  target?: string
  timeout_seconds?: number
  type?: "icmp" | "tcp" | "udp" | "dns" | "http" | "browser" | "a2a" | "noop" | "voice"
}

export interface Version {
  arch: string
  commit: string
  date: string
  go_version: string
  os: string
  version: string
}

export interface SsoCallbackRequest {
  code?: string
  state?: string
}

export type SsoCallbackResponse = void

export interface SsoLoginRequest {
  tenant?: string
}

export type SsoLoginResponse = void

export interface SsoLogoutRequest {
}

export type SsoLogoutResponse = void

export interface AgentEnrollRequest {
  body: JsonObject
}

export type AgentEnrollResponse = void

export interface AgentRotateRequest {
  body: JsonObject
}

export type AgentRotateResponse = void

export interface GetHealthzRequest {
}

export type GetHealthzResponse = Health

export interface IngestRumBeaconRequest {
  body: JsonObject
}

export type IngestRumBeaconResponse = JsonObject

export interface GetOpenApiRequest {
}

export type GetOpenApiResponse = void

export interface GetReadyzRequest {
}

export type GetReadyzResponse = Health

export interface StartA2aMeshRequest {
  body: JsonObject
}

export type StartA2aMeshResponse = JsonObject

export interface StartA2aSessionRequest {
  body: JsonObject
}

export type StartA2aSessionResponse = JsonObject

export interface ListPoliciesRequest {
}

export type ListPoliciesResponse = ABACPolicyList

export interface CreatePolicyRequest {
  body: ABACPolicy
}

export type CreatePolicyResponse = ABACPolicy

export interface DeletePolicyRequest {
}

export type DeletePolicyResponse = void

export interface ListAgentsRequest {
  after?: string
  limit?: number
}

export type ListAgentsResponse = AgentList

export interface MintAgentEnrollTokenRequest {
  body?: JsonObject
}

export type MintAgentEnrollTokenResponse = JsonObject

export interface GetAgentRequest {
}

export type GetAgentResponse = Agent

export interface PatchAgentRequest {
  body: AgentPatch
}

export type PatchAgentResponse = Agent

export interface DeleteAgentRequest {
}

export type DeleteAgentResponse = void

export interface AgentCiRequest {
  id: string
}

export type AgentCiResponse = JsonObject

export interface RevokeAgentRequest {
  id: string
}

export type RevokeAgentResponse = void

export interface AiAskRequest {
  body: AIAskRequest
}

export type AiAskResponse = AIAnswer

export interface AiAuthorRequest {
  body: AuthorRequest
}

export type AiAuthorResponse = TestProposal

export interface AiDiscoverRequest {
}

export type AiDiscoverResponse = DiscoverProposalList

export interface AiFeedbackRequest {
  body: AIFeedbackRequest
}

export type AiFeedbackResponse = void

export interface ListAlertsRequest {
}

export type ListAlertsResponse = AlertList

export interface CreateAlertRequest {
  body: AlertRequest
}

export type CreateAlertResponse = AlertRule

export interface ListActiveAlertsRequest {
}

export type ListActiveAlertsResponse = JsonObject

export interface AcknowledgeAlertRequest {
  body: JsonObject
}

export type AcknowledgeAlertResponse = JsonObject

export interface SilenceAlertRequest {
  body: JsonObject
}

export type SilenceAlertResponse = JsonObject

export interface ListMaintenanceWindowsRequest {
}

export type ListMaintenanceWindowsResponse = JsonObject

export interface UpsertMaintenanceWindowRequest {
  body: JsonObject
}

export type UpsertMaintenanceWindowResponse = JsonObject

export interface PreviewMaintenanceWindowsRequest {
  body: JsonObject
}

export type PreviewMaintenanceWindowsResponse = JsonObject

export interface DeleteMaintenanceWindowRequest {
  id: string
}

export type DeleteMaintenanceWindowResponse = void

export interface TestAlertChannelRequest {
  body: AlertChannelTestRequest
}

export type TestAlertChannelResponse = AlertChannelTestResponse

export interface GetAlertRequest {
}

export type GetAlertResponse = AlertRule

export interface UpdateAlertRequest {
  body: AlertRequest
}

export type UpdateAlertResponse = AlertRule

export interface DeleteAlertRequest {
}

export type DeleteAlertResponse = void

export interface ListAuditRequest {
  after?: number
  limit?: number
  actor?: string
  action?: string
  target?: string
}

export type ListAuditResponse = AuditList

export interface VerifyAuditRequest {
}

export type VerifyAuditResponse = AuditVerify

export interface ListBgpEventsRequest {
  prefix?: string
  asn?: string
  limit?: number
}

export type ListBgpEventsResponse = BGPEventList

export interface GetCarbonRequest {
}

export type GetCarbonResponse = JsonObject

export interface ListChangesRequest {
}

export type ListChangesResponse = ChangeEventList

export interface CmdbLookupRequest {
  key: string
}

export type CmdbLookupResponse = JsonObject

export interface RegisterCollectorRequest {
  body: CollectorRegisterRequest
}

export type RegisterCollectorResponse = CollectorRegistration

export interface ListComplianceResultsRequest {
}

export type ListComplianceResultsResponse = JsonObject

export interface ExportComplianceEvidenceRequest {
}

export type ExportComplianceEvidenceResponse = JsonObject

export interface GetCostSummaryRequest {
}

export type GetCostSummaryResponse = JsonObject

export interface ListDeviceMetricSummariesRequest {
  device?: string
  metric?: string
  limit?: number
}

export type ListDeviceMetricSummariesResponse = DeviceMetricSummaryList

export interface ListDevicesRequest {
  limit?: number
}

export type ListDevicesResponse = DeviceInventoryList

export interface GetV1DiagnosticsRequest {
}

export type GetV1DiagnosticsResponse = void

export interface GetV1DiagnosticsBundleRequest {
}

export type GetV1DiagnosticsBundleResponse = void

export interface ListScimTokensRequest {
}

export type ListScimTokensResponse = SCIMTokenList

export interface CreateScimTokenRequest {
  body: SCIMTokenCreate
}

export type CreateScimTokenResponse = SCIMTokenCreated

export interface RevokeScimTokenRequest {
}

export type RevokeScimTokenResponse = void

export interface ListEbpfServiceMapRequest {
  source?: string
  since?: string
  until?: string
  limit?: number
}

export type ListEbpfServiceMapResponse = EBPFServiceMap

export interface GetEditionsRequest {
}

export type GetEditionsResponse = JsonObject

export interface ListEndpointsRequest {
}

export type ListEndpointsResponse = JsonObject

export interface GetV1FairnessRequest {
}

export type GetV1FairnessResponse = void

export interface FlowAnomaliesRequest {
  exporter?: string
  direction?: "in" | "out"
  window?: string
  bucket?: string
  k?: number
  minBps?: number
}

export type FlowAnomaliesResponse = FlowAnomalyList

export interface FlowCapacityRequest {
  exporter?: string
  direction?: "in" | "out"
  window?: string
  bucket?: string
}

export type FlowCapacityResponse = FlowCapacityList

export interface FlowTopTalkersRequest {
  by?: "src" | "dst" | "pair" | "src_asn" | "dst_asn"
  window?: string
  limit?: number
}

export type FlowTopTalkersResponse = FlowTopList

export interface PromLabelValuesRequest {
  name: string
  match?: string
  start?: string
  end?: string
}

export type PromLabelValuesResponse = JsonObject

export interface PromLabelsRequest {
  match?: string
  start?: string
  end?: string
}

export type PromLabelsResponse = JsonObject

export interface PromLabelsFormRequest {
}

export type PromLabelsFormResponse = JsonObject

export interface PromMetadataRequest {
}

export type PromMetadataResponse = JsonObject

export interface PromQueryRequest {
  query?: string
  time?: string
}

export type PromQueryResponse = JsonObject

export interface PromQueryFormRequest {
}

export type PromQueryFormResponse = JsonObject

export interface PromQueryRangeRequest {
  query?: string
  start?: string
  end?: string
  step?: string
}

export type PromQueryRangeResponse = JsonObject

export interface PromQueryRangeFormRequest {
}

export type PromQueryRangeFormResponse = JsonObject

export interface PromSeriesRequest {
  match?: string
  start?: string
  end?: string
}

export type PromSeriesResponse = JsonObject

export interface PromSeriesFormRequest {
}

export type PromSeriesFormResponse = JsonObject

export interface PromBuildInfoRequest {
}

export type PromBuildInfoResponse = JsonObject

export interface GetHierarchyRequest {
}

export type GetHierarchyResponse = Hierarchy

export interface CreateHierarchyOrganizationRequest {
  body: HierarchyCreate
}

export type CreateHierarchyOrganizationResponse = HierarchyOrganizationFlat

export interface CreateHierarchyTeamRequest {
  id: string
  body: HierarchyCreate
}

export type CreateHierarchyTeamResponse = HierarchyTeamFlat

export interface CreateHierarchyProjectRequest {
  id: string
  body: HierarchyCreate
}

export type CreateHierarchyProjectResponse = HierarchyProject

export interface ListIncidentsRequest {
}

export type ListIncidentsResponse = IncidentList

export interface GetIncidentRequest {
}

export type GetIncidentResponse = Incident

export interface PatchIncidentRequest {
  body: IncidentPatch
}

export type PatchIncidentResponse = Incident

export interface ListIncidentChangesRequest {
}

export type ListIncidentChangesResponse = ChangeCandidateList

export interface IncidentCIsRequest {
  id: string
}

export type IncidentCIsResponse = JsonObject

export interface ListInventoryViewsRequest {
  surface?: "endpoints" | "targets" | "agents" | "incidents" | "alerts"
}

export type ListInventoryViewsResponse = InventorySavedViewList

export interface CreateInventoryViewRequest {
  body: InventorySavedViewInput
}

export type CreateInventoryViewResponse = InventorySavedView

export interface GetInventoryViewRequest {
  id: string
}

export type GetInventoryViewResponse = InventorySavedView

export interface GetIsolationStatusRequest {
}

export type GetIsolationStatusResponse = IsolationStatus

export interface PostV1LifecycleEraseRequest {
}

export type PostV1LifecycleEraseResponse = void

export interface GetV1LifecycleExportRequest {
}

export type GetV1LifecycleExportResponse = void

export interface GetV1LifecycleRetentionRequest {
}

export type GetV1LifecycleRetentionResponse = LifecycleStatus

export interface PutV1LifecycleRetentionRequest {
  body: LifecycleRetentionInput
}

export type PutV1LifecycleRetentionResponse = LifecycleStatus

export interface PostV1LifecycleSubjectsEraseRequest {
  body: JsonObject
}

export type PostV1LifecycleSubjectsEraseResponse = void

export interface PostV1LifecycleSubjectsExportRequest {
  body: JsonObject
}

export type PostV1LifecycleSubjectsExportResponse = void

export interface GetMeRequest {
}

export type GetMeResponse = Me

export interface GetOncallStatusRequest {
}

export type GetOncallStatusResponse = OncallStatus

export interface TestOncallConnectorRequest {
  body: OncallTestRequest
}

export type TestOncallConnectorResponse = OncallTestResponse

export interface ListOtlpTokensRequest {
}

export type ListOtlpTokensResponse = JsonObject

export interface CreateOtlpTokenRequest {
  body?: JsonObject
}

export type CreateOtlpTokenResponse = JsonObject

export interface RevokeOtlpTokenRequest {
  id: string
}

export type RevokeOtlpTokenResponse = void

export interface OtlpLogsRequest {
  service?: string
  traceId?: string
  since?: string
  until?: string
  limit?: number
  minSeverity?: number
}

export type OtlpLogsResponse = JsonObject

export interface OtlpTracesRequest {
  service?: string
  traceId?: string
  since?: string
  until?: string
  limit?: number
}

export type OtlpTracesResponse = JsonObject

export interface GetOutagesRequest {
}

export type GetOutagesResponse = JsonObject

export interface PromFederateRequest {
  match?: string
}

export type PromFederateResponse = Response

export interface PromRemoteWriteRequest {
}

export type PromRemoteWriteResponse = void

export interface GetV1RemediationProposalsRequest {
}

export type GetV1RemediationProposalsResponse = void

export interface PostV1RemediationProposalsRequest {
}

export type PostV1RemediationProposalsResponse = void

export interface GetV1RemediationProposalsIdRequest {
}

export type GetV1RemediationProposalsIdResponse = void

export interface PostV1RemediationProposalsIdApproveRequest {
}

export type PostV1RemediationProposalsIdApproveResponse = void

export interface PostV1RemediationProposalsIdRejectRequest {
}

export type PostV1RemediationProposalsIdRejectResponse = void

export interface ListLatestResultsRequest {
}

export type ListLatestResultsResponse = JsonObject

export interface ListRolloutsRequest {
}

export type ListRolloutsResponse = JsonObject

export interface CreateRolloutRequest {
  body: JsonObject
}

export type CreateRolloutResponse = JsonObject

export interface GetRolloutRequest {
  id: string
}

export type GetRolloutResponse = JsonObject

export interface AdvanceRolloutRequest {
  id: string
}

export type AdvanceRolloutResponse = JsonObject

export interface HaltRolloutRequest {
  id: string
  body?: JsonObject
}

export type HaltRolloutResponse = JsonObject

export interface ResumeRolloutRequest {
  id: string
  body?: JsonObject
}

export type ResumeRolloutResponse = JsonObject

export interface VerifyRolloutRequest {
  id: string
}

export type VerifyRolloutResponse = JsonObject

export interface GetRumRequest {
}

export type GetRumResponse = JsonObject

export interface GetSecretsHealthRequest {
}

export type GetSecretsHealthResponse = JsonObject

export interface GetV1SecurityKeysRequest {
}

export type GetV1SecurityKeysResponse = void

export interface PostV1SecurityKeysRotateRequest {
}

export type PostV1SecurityKeysRotateResponse = void

export interface GetSiemStatusRequest {
}

export type GetSiemStatusResponse = SIEMStatus

export interface ListSlOsRequest {
}

export type ListSlOsResponse = JsonObject

export interface ExportOpenSloRequest {
}

export type ExportOpenSloResponse = Response

export interface ListTestsRequest {
  after?: string
  limit?: number
}

export type ListTestsResponse = TestList

export interface CreateTestRequest {
  q?: string
  cause?: "all" | "impaired" | "wifi" | "local" | "isp" | "network" | "none"
  body: TestRequest
}

export type CreateTestResponse = Test

export interface GetTestBundleRequest {
}

export type GetTestBundleResponse = JsonObject

export interface GetTestRequest {
}

export type GetTestResponse = Test

export interface UpdateTestRequest {
  body: TestRequest
}

export type UpdateTestResponse = Test

export interface DeleteTestRequest {
}

export type DeleteTestResponse = void

export interface GetTestPathRequest {
}

export type GetTestPathResponse = Path

export interface DiscoverTestPathRequest {
}

export type DiscoverTestPathResponse = Path

export interface ListThreatDetectionsRequest {
}

export type ListThreatDetectionsResponse = JsonObject

export interface GetThreatIntelStatusRequest {
}

export type GetThreatIntelStatusResponse = JsonObject

export interface ListTlsPostureRequest {
}

export type ListTlsPostureResponse = JsonObject

export interface GetTopologyRequest {
  at?: string
}

export type GetTopologyResponse = JsonObject

export interface SimulateWhatIfRequest {
  body: JsonObject
}

export type SimulateWhatIfResponse = JsonObject

export interface GetVersionRequest {
}

export type GetVersionResponse = Version

export interface SDKClientOptions {
  baseUrl?: string
  token?: string
  tenant?: string
  fetch?: typeof fetch
  userAgent?: string
}

export class ProbectlSDKClient {
  private readonly baseUrl: string
  private readonly fetcher: typeof fetch

  constructor(private readonly options: SDKClientOptions = {}) {
    this.baseUrl = (options.baseUrl ?? '').replace(/\/$/, '')
    this.fetcher = options.fetch ?? fetch
  }

  async ssoCallback(request: SsoCallbackRequest = {}): Promise<SsoCallbackResponse> {
    let path = "/auth/callback"
    const query = new URLSearchParams()
    if (request.code !== undefined) query.set("code", String(request.code))
    if (request.state !== undefined) query.set("state", String(request.state))
    await this.request("GET", path, query, undefined)
  }

  async ssoLogin(request: SsoLoginRequest = {}): Promise<SsoLoginResponse> {
    let path = "/auth/login"
    const query = new URLSearchParams()
    if (request.tenant !== undefined) query.set("tenant", String(request.tenant))
    await this.request("GET", path, query, undefined)
  }

  async ssoLogout(): Promise<SsoLogoutResponse> {
    let path = "/auth/logout"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async agentEnroll(request: AgentEnrollRequest): Promise<AgentEnrollResponse> {
    let path = "/enroll/agent"
    const query = new URLSearchParams()
    await this.request("POST", path, query, request.body)
  }

  async agentRotate(request: AgentRotateRequest): Promise<AgentRotateResponse> {
    let path = "/enroll/agent/rotate"
    const query = new URLSearchParams()
    await this.request("POST", path, query, request.body)
  }

  async getHealthz(): Promise<GetHealthzResponse> {
    let path = "/healthz"
    const query = new URLSearchParams()
    return this.requestJSON<GetHealthzResponse>("GET", path, query, undefined)
  }

  async ingestRumBeacon(request: IngestRumBeaconRequest): Promise<IngestRumBeaconResponse> {
    let path = "/ingest/rum"
    const query = new URLSearchParams()
    return this.requestJSON<IngestRumBeaconResponse>("POST", path, query, request.body)
  }

  async getOpenApi(): Promise<GetOpenApiResponse> {
    let path = "/openapi.json"
    const query = new URLSearchParams()
    return this.requestJSON<GetOpenApiResponse>("GET", path, query, undefined)
  }

  async getReadyz(): Promise<GetReadyzResponse> {
    let path = "/readyz"
    const query = new URLSearchParams()
    return this.requestJSON<GetReadyzResponse>("GET", path, query, undefined)
  }

  async startA2aMesh(request: StartA2aMeshRequest): Promise<StartA2aMeshResponse> {
    let path = "/v1/a2a/mesh"
    const query = new URLSearchParams()
    return this.requestJSON<StartA2aMeshResponse>("POST", path, query, request.body)
  }

  async startA2aSession(request: StartA2aSessionRequest): Promise<StartA2aSessionResponse> {
    let path = "/v1/a2a/sessions"
    const query = new URLSearchParams()
    return this.requestJSON<StartA2aSessionResponse>("POST", path, query, request.body)
  }

  async listPolicies(): Promise<ListPoliciesResponse> {
    let path = "/v1/abac/policies"
    const query = new URLSearchParams()
    return this.requestJSON<ListPoliciesResponse>("GET", path, query, undefined)
  }

  async createPolicy(request: CreatePolicyRequest): Promise<CreatePolicyResponse> {
    let path = "/v1/abac/policies"
    const query = new URLSearchParams()
    return this.requestJSON<CreatePolicyResponse>("POST", path, query, request.body)
  }

  async deletePolicy(): Promise<DeletePolicyResponse> {
    let path = "/v1/abac/policies/{id}"
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async listAgents(request: ListAgentsRequest = {}): Promise<ListAgentsResponse> {
    let path = "/v1/agents"
    const query = new URLSearchParams()
    if (request.after !== undefined) query.set("after", String(request.after))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<ListAgentsResponse>("GET", path, query, undefined)
  }

  async mintAgentEnrollToken(request: MintAgentEnrollTokenRequest = {}): Promise<MintAgentEnrollTokenResponse> {
    let path = "/v1/agents/enroll-tokens"
    const query = new URLSearchParams()
    return this.requestJSON<MintAgentEnrollTokenResponse>("POST", path, query, request.body)
  }

  async getAgent(): Promise<GetAgentResponse> {
    let path = "/v1/agents/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<GetAgentResponse>("GET", path, query, undefined)
  }

  async patchAgent(request: PatchAgentRequest): Promise<PatchAgentResponse> {
    let path = "/v1/agents/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<PatchAgentResponse>("PATCH", path, query, request.body)
  }

  async deleteAgent(): Promise<DeleteAgentResponse> {
    let path = "/v1/agents/{id}"
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async agentCi(request: AgentCiRequest): Promise<AgentCiResponse> {
    let path = "/v1/agents/{id}/ci"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<AgentCiResponse>("GET", path, query, undefined)
  }

  async revokeAgent(request: RevokeAgentRequest): Promise<RevokeAgentResponse> {
    let path = "/v1/agents/{id}/revoke"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async aiAsk(request: AiAskRequest): Promise<AiAskResponse> {
    let path = "/v1/ai/ask"
    const query = new URLSearchParams()
    return this.requestJSON<AiAskResponse>("POST", path, query, request.body)
  }

  async aiAuthor(request: AiAuthorRequest): Promise<AiAuthorResponse> {
    let path = "/v1/ai/author"
    const query = new URLSearchParams()
    return this.requestJSON<AiAuthorResponse>("POST", path, query, request.body)
  }

  async aiDiscover(): Promise<AiDiscoverResponse> {
    let path = "/v1/ai/discover"
    const query = new URLSearchParams()
    return this.requestJSON<AiDiscoverResponse>("POST", path, query, undefined)
  }

  async aiFeedback(request: AiFeedbackRequest): Promise<AiFeedbackResponse> {
    let path = "/v1/ai/feedback"
    const query = new URLSearchParams()
    await this.request("POST", path, query, request.body)
  }

  async listAlerts(): Promise<ListAlertsResponse> {
    let path = "/v1/alerts"
    const query = new URLSearchParams()
    return this.requestJSON<ListAlertsResponse>("GET", path, query, undefined)
  }

  async createAlert(request: CreateAlertRequest): Promise<CreateAlertResponse> {
    let path = "/v1/alerts"
    const query = new URLSearchParams()
    return this.requestJSON<CreateAlertResponse>("POST", path, query, request.body)
  }

  async listActiveAlerts(): Promise<ListActiveAlertsResponse> {
    let path = "/v1/alerts/active"
    const query = new URLSearchParams()
    return this.requestJSON<ListActiveAlertsResponse>("GET", path, query, undefined)
  }

  async acknowledgeAlert(request: AcknowledgeAlertRequest): Promise<AcknowledgeAlertResponse> {
    let path = "/v1/alerts/active/ack"
    const query = new URLSearchParams()
    return this.requestJSON<AcknowledgeAlertResponse>("POST", path, query, request.body)
  }

  async silenceAlert(request: SilenceAlertRequest): Promise<SilenceAlertResponse> {
    let path = "/v1/alerts/active/silence"
    const query = new URLSearchParams()
    return this.requestJSON<SilenceAlertResponse>("POST", path, query, request.body)
  }

  async listMaintenanceWindows(): Promise<ListMaintenanceWindowsResponse> {
    let path = "/v1/alerts/maintenance"
    const query = new URLSearchParams()
    return this.requestJSON<ListMaintenanceWindowsResponse>("GET", path, query, undefined)
  }

  async upsertMaintenanceWindow(request: UpsertMaintenanceWindowRequest): Promise<UpsertMaintenanceWindowResponse> {
    let path = "/v1/alerts/maintenance"
    const query = new URLSearchParams()
    return this.requestJSON<UpsertMaintenanceWindowResponse>("POST", path, query, request.body)
  }

  async previewMaintenanceWindows(request: PreviewMaintenanceWindowsRequest): Promise<PreviewMaintenanceWindowsResponse> {
    let path = "/v1/alerts/maintenance/preview"
    const query = new URLSearchParams()
    return this.requestJSON<PreviewMaintenanceWindowsResponse>("POST", path, query, request.body)
  }

  async deleteMaintenanceWindow(request: DeleteMaintenanceWindowRequest): Promise<DeleteMaintenanceWindowResponse> {
    let path = "/v1/alerts/maintenance/{id}"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async testAlertChannel(request: TestAlertChannelRequest): Promise<TestAlertChannelResponse> {
    let path = "/v1/alerts/test-channel"
    const query = new URLSearchParams()
    return this.requestJSON<TestAlertChannelResponse>("POST", path, query, request.body)
  }

  async getAlert(): Promise<GetAlertResponse> {
    let path = "/v1/alerts/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<GetAlertResponse>("GET", path, query, undefined)
  }

  async updateAlert(request: UpdateAlertRequest): Promise<UpdateAlertResponse> {
    let path = "/v1/alerts/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<UpdateAlertResponse>("PUT", path, query, request.body)
  }

  async deleteAlert(): Promise<DeleteAlertResponse> {
    let path = "/v1/alerts/{id}"
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async listAudit(request: ListAuditRequest = {}): Promise<ListAuditResponse> {
    let path = "/v1/audit"
    const query = new URLSearchParams()
    if (request.after !== undefined) query.set("after", String(request.after))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    if (request.actor !== undefined) query.set("actor", String(request.actor))
    if (request.action !== undefined) query.set("action", String(request.action))
    if (request.target !== undefined) query.set("target", String(request.target))
    return this.requestJSON<ListAuditResponse>("GET", path, query, undefined)
  }

  async verifyAudit(): Promise<VerifyAuditResponse> {
    let path = "/v1/audit/verify"
    const query = new URLSearchParams()
    return this.requestJSON<VerifyAuditResponse>("GET", path, query, undefined)
  }

  async listBgpEvents(request: ListBgpEventsRequest = {}): Promise<ListBgpEventsResponse> {
    let path = "/v1/bgp/events"
    const query = new URLSearchParams()
    if (request.prefix !== undefined) query.set("prefix", String(request.prefix))
    if (request.asn !== undefined) query.set("asn", String(request.asn))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<ListBgpEventsResponse>("GET", path, query, undefined)
  }

  async getCarbon(): Promise<GetCarbonResponse> {
    let path = "/v1/carbon"
    const query = new URLSearchParams()
    return this.requestJSON<GetCarbonResponse>("GET", path, query, undefined)
  }

  async listChanges(): Promise<ListChangesResponse> {
    let path = "/v1/changes"
    const query = new URLSearchParams()
    return this.requestJSON<ListChangesResponse>("GET", path, query, undefined)
  }

  async cmdbLookup(request: CmdbLookupRequest): Promise<CmdbLookupResponse> {
    let path = "/v1/cmdb/lookup"
    const query = new URLSearchParams()
    if (request.key !== undefined) query.set("key", String(request.key))
    return this.requestJSON<CmdbLookupResponse>("GET", path, query, undefined)
  }

  async registerCollector(request: RegisterCollectorRequest): Promise<RegisterCollectorResponse> {
    let path = "/v1/collectors/register"
    const query = new URLSearchParams()
    return this.requestJSON<RegisterCollectorResponse>("POST", path, query, request.body)
  }

  async listComplianceResults(): Promise<ListComplianceResultsResponse> {
    let path = "/v1/compliance"
    const query = new URLSearchParams()
    return this.requestJSON<ListComplianceResultsResponse>("GET", path, query, undefined)
  }

  async exportComplianceEvidence(): Promise<ExportComplianceEvidenceResponse> {
    let path = "/v1/compliance/evidence"
    const query = new URLSearchParams()
    return this.requestJSON<ExportComplianceEvidenceResponse>("GET", path, query, undefined)
  }

  async getCostSummary(): Promise<GetCostSummaryResponse> {
    let path = "/v1/cost/summary"
    const query = new URLSearchParams()
    return this.requestJSON<GetCostSummaryResponse>("GET", path, query, undefined)
  }

  async listDeviceMetricSummaries(request: ListDeviceMetricSummariesRequest = {}): Promise<ListDeviceMetricSummariesResponse> {
    let path = "/v1/device/metrics"
    const query = new URLSearchParams()
    if (request.device !== undefined) query.set("device", String(request.device))
    if (request.metric !== undefined) query.set("metric", String(request.metric))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<ListDeviceMetricSummariesResponse>("GET", path, query, undefined)
  }

  async listDevices(request: ListDevicesRequest = {}): Promise<ListDevicesResponse> {
    let path = "/v1/devices"
    const query = new URLSearchParams()
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<ListDevicesResponse>("GET", path, query, undefined)
  }

  async getV1Diagnostics(): Promise<GetV1DiagnosticsResponse> {
    let path = "/v1/diagnostics"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async getV1DiagnosticsBundle(): Promise<GetV1DiagnosticsBundleResponse> {
    let path = "/v1/diagnostics/bundle"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async listScimTokens(): Promise<ListScimTokensResponse> {
    let path = "/v1/directory/scim-tokens"
    const query = new URLSearchParams()
    return this.requestJSON<ListScimTokensResponse>("GET", path, query, undefined)
  }

  async createScimToken(request: CreateScimTokenRequest): Promise<CreateScimTokenResponse> {
    let path = "/v1/directory/scim-tokens"
    const query = new URLSearchParams()
    return this.requestJSON<CreateScimTokenResponse>("POST", path, query, request.body)
  }

  async revokeScimToken(): Promise<RevokeScimTokenResponse> {
    let path = "/v1/directory/scim-tokens/{id}"
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async listEbpfServiceMap(request: ListEbpfServiceMapRequest = {}): Promise<ListEbpfServiceMapResponse> {
    let path = "/v1/ebpf/service-map"
    const query = new URLSearchParams()
    if (request.source !== undefined) query.set("source", String(request.source))
    if (request.since !== undefined) query.set("since", String(request.since))
    if (request.until !== undefined) query.set("until", String(request.until))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<ListEbpfServiceMapResponse>("GET", path, query, undefined)
  }

  async getEditions(): Promise<GetEditionsResponse> {
    let path = "/v1/editions"
    const query = new URLSearchParams()
    return this.requestJSON<GetEditionsResponse>("GET", path, query, undefined)
  }

  async listEndpoints(): Promise<ListEndpointsResponse> {
    let path = "/v1/endpoints"
    const query = new URLSearchParams()
    return this.requestJSON<ListEndpointsResponse>("GET", path, query, undefined)
  }

  async getV1Fairness(): Promise<GetV1FairnessResponse> {
    let path = "/v1/fairness"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async flowAnomalies(request: FlowAnomaliesRequest = {}): Promise<FlowAnomaliesResponse> {
    let path = "/v1/flows/anomalies"
    const query = new URLSearchParams()
    if (request.exporter !== undefined) query.set("exporter", String(request.exporter))
    if (request.direction !== undefined) query.set("direction", String(request.direction))
    if (request.window !== undefined) query.set("window", String(request.window))
    if (request.bucket !== undefined) query.set("bucket", String(request.bucket))
    if (request.k !== undefined) query.set("k", String(request.k))
    if (request.minBps !== undefined) query.set("min_bps", String(request.minBps))
    return this.requestJSON<FlowAnomaliesResponse>("GET", path, query, undefined)
  }

  async flowCapacity(request: FlowCapacityRequest = {}): Promise<FlowCapacityResponse> {
    let path = "/v1/flows/capacity"
    const query = new URLSearchParams()
    if (request.exporter !== undefined) query.set("exporter", String(request.exporter))
    if (request.direction !== undefined) query.set("direction", String(request.direction))
    if (request.window !== undefined) query.set("window", String(request.window))
    if (request.bucket !== undefined) query.set("bucket", String(request.bucket))
    return this.requestJSON<FlowCapacityResponse>("GET", path, query, undefined)
  }

  async flowTopTalkers(request: FlowTopTalkersRequest = {}): Promise<FlowTopTalkersResponse> {
    let path = "/v1/flows/top"
    const query = new URLSearchParams()
    if (request.by !== undefined) query.set("by", String(request.by))
    if (request.window !== undefined) query.set("window", String(request.window))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<FlowTopTalkersResponse>("GET", path, query, undefined)
  }

  async promLabelValues(request: PromLabelValuesRequest): Promise<PromLabelValuesResponse> {
    let path = "/v1/grafana/api/v1/label/{name}/values"
    path = path.replace("{name}", encodeURIComponent(String(request.name)))
    const query = new URLSearchParams()
    if (request.match !== undefined) query.set("match[]", String(request.match))
    if (request.start !== undefined) query.set("start", String(request.start))
    if (request.end !== undefined) query.set("end", String(request.end))
    return this.requestJSON<PromLabelValuesResponse>("GET", path, query, undefined)
  }

  async promLabels(request: PromLabelsRequest = {}): Promise<PromLabelsResponse> {
    let path = "/v1/grafana/api/v1/labels"
    const query = new URLSearchParams()
    if (request.match !== undefined) query.set("match[]", String(request.match))
    if (request.start !== undefined) query.set("start", String(request.start))
    if (request.end !== undefined) query.set("end", String(request.end))
    return this.requestJSON<PromLabelsResponse>("GET", path, query, undefined)
  }

  async promLabelsForm(): Promise<PromLabelsFormResponse> {
    let path = "/v1/grafana/api/v1/labels"
    const query = new URLSearchParams()
    return this.requestJSON<PromLabelsFormResponse>("POST", path, query, undefined)
  }

  async promMetadata(): Promise<PromMetadataResponse> {
    let path = "/v1/grafana/api/v1/metadata"
    const query = new URLSearchParams()
    return this.requestJSON<PromMetadataResponse>("GET", path, query, undefined)
  }

  async promQuery(request: PromQueryRequest = {}): Promise<PromQueryResponse> {
    let path = "/v1/grafana/api/v1/query"
    const query = new URLSearchParams()
    if (request.query !== undefined) query.set("query", String(request.query))
    if (request.time !== undefined) query.set("time", String(request.time))
    return this.requestJSON<PromQueryResponse>("GET", path, query, undefined)
  }

  async promQueryForm(): Promise<PromQueryFormResponse> {
    let path = "/v1/grafana/api/v1/query"
    const query = new URLSearchParams()
    return this.requestJSON<PromQueryFormResponse>("POST", path, query, undefined)
  }

  async promQueryRange(request: PromQueryRangeRequest = {}): Promise<PromQueryRangeResponse> {
    let path = "/v1/grafana/api/v1/query_range"
    const query = new URLSearchParams()
    if (request.query !== undefined) query.set("query", String(request.query))
    if (request.start !== undefined) query.set("start", String(request.start))
    if (request.end !== undefined) query.set("end", String(request.end))
    if (request.step !== undefined) query.set("step", String(request.step))
    return this.requestJSON<PromQueryRangeResponse>("GET", path, query, undefined)
  }

  async promQueryRangeForm(): Promise<PromQueryRangeFormResponse> {
    let path = "/v1/grafana/api/v1/query_range"
    const query = new URLSearchParams()
    return this.requestJSON<PromQueryRangeFormResponse>("POST", path, query, undefined)
  }

  async promSeries(request: PromSeriesRequest = {}): Promise<PromSeriesResponse> {
    let path = "/v1/grafana/api/v1/series"
    const query = new URLSearchParams()
    if (request.match !== undefined) query.set("match[]", String(request.match))
    if (request.start !== undefined) query.set("start", String(request.start))
    if (request.end !== undefined) query.set("end", String(request.end))
    return this.requestJSON<PromSeriesResponse>("GET", path, query, undefined)
  }

  async promSeriesForm(): Promise<PromSeriesFormResponse> {
    let path = "/v1/grafana/api/v1/series"
    const query = new URLSearchParams()
    return this.requestJSON<PromSeriesFormResponse>("POST", path, query, undefined)
  }

  async promBuildInfo(): Promise<PromBuildInfoResponse> {
    let path = "/v1/grafana/api/v1/status/buildinfo"
    const query = new URLSearchParams()
    return this.requestJSON<PromBuildInfoResponse>("GET", path, query, undefined)
  }

  async getHierarchy(): Promise<GetHierarchyResponse> {
    let path = "/v1/hierarchy"
    const query = new URLSearchParams()
    return this.requestJSON<GetHierarchyResponse>("GET", path, query, undefined)
  }

  async createHierarchyOrganization(request: CreateHierarchyOrganizationRequest): Promise<CreateHierarchyOrganizationResponse> {
    let path = "/v1/hierarchy/orgs"
    const query = new URLSearchParams()
    return this.requestJSON<CreateHierarchyOrganizationResponse>("POST", path, query, request.body)
  }

  async createHierarchyTeam(request: CreateHierarchyTeamRequest): Promise<CreateHierarchyTeamResponse> {
    let path = "/v1/hierarchy/orgs/{id}/teams"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<CreateHierarchyTeamResponse>("POST", path, query, request.body)
  }

  async createHierarchyProject(request: CreateHierarchyProjectRequest): Promise<CreateHierarchyProjectResponse> {
    let path = "/v1/hierarchy/teams/{id}/projects"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<CreateHierarchyProjectResponse>("POST", path, query, request.body)
  }

  async listIncidents(): Promise<ListIncidentsResponse> {
    let path = "/v1/incidents"
    const query = new URLSearchParams()
    return this.requestJSON<ListIncidentsResponse>("GET", path, query, undefined)
  }

  async getIncident(): Promise<GetIncidentResponse> {
    let path = "/v1/incidents/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<GetIncidentResponse>("GET", path, query, undefined)
  }

  async patchIncident(request: PatchIncidentRequest): Promise<PatchIncidentResponse> {
    let path = "/v1/incidents/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<PatchIncidentResponse>("PATCH", path, query, request.body)
  }

  async listIncidentChanges(): Promise<ListIncidentChangesResponse> {
    let path = "/v1/incidents/{id}/changes"
    const query = new URLSearchParams()
    return this.requestJSON<ListIncidentChangesResponse>("GET", path, query, undefined)
  }

  async incidentCIs(request: IncidentCIsRequest): Promise<IncidentCIsResponse> {
    let path = "/v1/incidents/{id}/cis"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<IncidentCIsResponse>("GET", path, query, undefined)
  }

  async listInventoryViews(request: ListInventoryViewsRequest = {}): Promise<ListInventoryViewsResponse> {
    let path = "/v1/inventory/views"
    const query = new URLSearchParams()
    if (request.surface !== undefined) query.set("surface", String(request.surface))
    return this.requestJSON<ListInventoryViewsResponse>("GET", path, query, undefined)
  }

  async createInventoryView(request: CreateInventoryViewRequest): Promise<CreateInventoryViewResponse> {
    let path = "/v1/inventory/views"
    const query = new URLSearchParams()
    return this.requestJSON<CreateInventoryViewResponse>("POST", path, query, request.body)
  }

  async getInventoryView(request: GetInventoryViewRequest): Promise<GetInventoryViewResponse> {
    let path = "/v1/inventory/views/{id}"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<GetInventoryViewResponse>("GET", path, query, undefined)
  }

  async getIsolationStatus(): Promise<GetIsolationStatusResponse> {
    let path = "/v1/isolation/status"
    const query = new URLSearchParams()
    return this.requestJSON<GetIsolationStatusResponse>("GET", path, query, undefined)
  }

  async postV1LifecycleErase(): Promise<PostV1LifecycleEraseResponse> {
    let path = "/v1/lifecycle/erase"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async getV1LifecycleExport(): Promise<GetV1LifecycleExportResponse> {
    let path = "/v1/lifecycle/export"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async getV1LifecycleRetention(): Promise<GetV1LifecycleRetentionResponse> {
    let path = "/v1/lifecycle/retention"
    const query = new URLSearchParams()
    return this.requestJSON<GetV1LifecycleRetentionResponse>("GET", path, query, undefined)
  }

  async putV1LifecycleRetention(request: PutV1LifecycleRetentionRequest): Promise<PutV1LifecycleRetentionResponse> {
    let path = "/v1/lifecycle/retention"
    const query = new URLSearchParams()
    return this.requestJSON<PutV1LifecycleRetentionResponse>("PUT", path, query, request.body)
  }

  async postV1LifecycleSubjectsErase(request: PostV1LifecycleSubjectsEraseRequest): Promise<PostV1LifecycleSubjectsEraseResponse> {
    let path = "/v1/lifecycle/subjects/erase"
    const query = new URLSearchParams()
    await this.request("POST", path, query, request.body)
  }

  async postV1LifecycleSubjectsExport(request: PostV1LifecycleSubjectsExportRequest): Promise<PostV1LifecycleSubjectsExportResponse> {
    let path = "/v1/lifecycle/subjects/export"
    const query = new URLSearchParams()
    await this.request("POST", path, query, request.body)
  }

  async getMe(): Promise<GetMeResponse> {
    let path = "/v1/me"
    const query = new URLSearchParams()
    return this.requestJSON<GetMeResponse>("GET", path, query, undefined)
  }

  async getOncallStatus(): Promise<GetOncallStatusResponse> {
    let path = "/v1/oncall/status"
    const query = new URLSearchParams()
    return this.requestJSON<GetOncallStatusResponse>("GET", path, query, undefined)
  }

  async testOncallConnector(request: TestOncallConnectorRequest): Promise<TestOncallConnectorResponse> {
    let path = "/v1/oncall/test"
    const query = new URLSearchParams()
    return this.requestJSON<TestOncallConnectorResponse>("POST", path, query, request.body)
  }

  async listOtlpTokens(): Promise<ListOtlpTokensResponse> {
    let path = "/v1/otlp-tokens"
    const query = new URLSearchParams()
    return this.requestJSON<ListOtlpTokensResponse>("GET", path, query, undefined)
  }

  async createOtlpToken(request: CreateOtlpTokenRequest = {}): Promise<CreateOtlpTokenResponse> {
    let path = "/v1/otlp-tokens"
    const query = new URLSearchParams()
    return this.requestJSON<CreateOtlpTokenResponse>("POST", path, query, request.body)
  }

  async revokeOtlpToken(request: RevokeOtlpTokenRequest): Promise<RevokeOtlpTokenResponse> {
    let path = "/v1/otlp-tokens/{id}"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async otlpLogs(request: OtlpLogsRequest = {}): Promise<OtlpLogsResponse> {
    let path = "/v1/otlp/logs"
    const query = new URLSearchParams()
    if (request.service !== undefined) query.set("service", String(request.service))
    if (request.traceId !== undefined) query.set("trace_id", String(request.traceId))
    if (request.since !== undefined) query.set("since", String(request.since))
    if (request.until !== undefined) query.set("until", String(request.until))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    if (request.minSeverity !== undefined) query.set("min_severity", String(request.minSeverity))
    return this.requestJSON<OtlpLogsResponse>("GET", path, query, undefined)
  }

  async otlpTraces(request: OtlpTracesRequest = {}): Promise<OtlpTracesResponse> {
    let path = "/v1/otlp/traces"
    const query = new URLSearchParams()
    if (request.service !== undefined) query.set("service", String(request.service))
    if (request.traceId !== undefined) query.set("trace_id", String(request.traceId))
    if (request.since !== undefined) query.set("since", String(request.since))
    if (request.until !== undefined) query.set("until", String(request.until))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<OtlpTracesResponse>("GET", path, query, undefined)
  }

  async getOutages(): Promise<GetOutagesResponse> {
    let path = "/v1/outages"
    const query = new URLSearchParams()
    return this.requestJSON<GetOutagesResponse>("GET", path, query, undefined)
  }

  async promFederate(request: PromFederateRequest = {}): Promise<PromFederateResponse> {
    let path = "/v1/prometheus/federate"
    const query = new URLSearchParams()
    if (request.match !== undefined) query.set("match[]", String(request.match))
    return this.request("GET", path, query, undefined)
  }

  async promRemoteWrite(): Promise<PromRemoteWriteResponse> {
    let path = "/v1/prometheus/write"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async getV1RemediationProposals(): Promise<GetV1RemediationProposalsResponse> {
    let path = "/v1/remediation/proposals"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async postV1RemediationProposals(): Promise<PostV1RemediationProposalsResponse> {
    let path = "/v1/remediation/proposals"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async getV1RemediationProposalsId(): Promise<GetV1RemediationProposalsIdResponse> {
    let path = "/v1/remediation/proposals/{id}"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async postV1RemediationProposalsIdApprove(): Promise<PostV1RemediationProposalsIdApproveResponse> {
    let path = "/v1/remediation/proposals/{id}/approve"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async postV1RemediationProposalsIdReject(): Promise<PostV1RemediationProposalsIdRejectResponse> {
    let path = "/v1/remediation/proposals/{id}/reject"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async listLatestResults(): Promise<ListLatestResultsResponse> {
    let path = "/v1/results/latest"
    const query = new URLSearchParams()
    return this.requestJSON<ListLatestResultsResponse>("GET", path, query, undefined)
  }

  async listRollouts(): Promise<ListRolloutsResponse> {
    let path = "/v1/rollouts"
    const query = new URLSearchParams()
    return this.requestJSON<ListRolloutsResponse>("GET", path, query, undefined)
  }

  async createRollout(request: CreateRolloutRequest): Promise<CreateRolloutResponse> {
    let path = "/v1/rollouts"
    const query = new URLSearchParams()
    return this.requestJSON<CreateRolloutResponse>("POST", path, query, request.body)
  }

  async getRollout(request: GetRolloutRequest): Promise<GetRolloutResponse> {
    let path = "/v1/rollouts/{id}"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<GetRolloutResponse>("GET", path, query, undefined)
  }

  async advanceRollout(request: AdvanceRolloutRequest): Promise<AdvanceRolloutResponse> {
    let path = "/v1/rollouts/{id}/advance"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<AdvanceRolloutResponse>("POST", path, query, undefined)
  }

  async haltRollout(request: HaltRolloutRequest): Promise<HaltRolloutResponse> {
    let path = "/v1/rollouts/{id}/halt"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<HaltRolloutResponse>("POST", path, query, request.body)
  }

  async resumeRollout(request: ResumeRolloutRequest): Promise<ResumeRolloutResponse> {
    let path = "/v1/rollouts/{id}/resume"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<ResumeRolloutResponse>("POST", path, query, request.body)
  }

  async verifyRollout(request: VerifyRolloutRequest): Promise<VerifyRolloutResponse> {
    let path = "/v1/rollouts/{id}/verify"
    path = path.replace("{id}", encodeURIComponent(String(request.id)))
    const query = new URLSearchParams()
    return this.requestJSON<VerifyRolloutResponse>("POST", path, query, undefined)
  }

  async getRum(): Promise<GetRumResponse> {
    let path = "/v1/rum"
    const query = new URLSearchParams()
    return this.requestJSON<GetRumResponse>("GET", path, query, undefined)
  }

  async getSecretsHealth(): Promise<GetSecretsHealthResponse> {
    let path = "/v1/secrets/health"
    const query = new URLSearchParams()
    return this.requestJSON<GetSecretsHealthResponse>("GET", path, query, undefined)
  }

  async getV1SecurityKeys(): Promise<GetV1SecurityKeysResponse> {
    let path = "/v1/security/keys"
    const query = new URLSearchParams()
    await this.request("GET", path, query, undefined)
  }

  async postV1SecurityKeysRotate(): Promise<PostV1SecurityKeysRotateResponse> {
    let path = "/v1/security/keys/rotate"
    const query = new URLSearchParams()
    await this.request("POST", path, query, undefined)
  }

  async getSiemStatus(): Promise<GetSiemStatusResponse> {
    let path = "/v1/siem/status"
    const query = new URLSearchParams()
    return this.requestJSON<GetSiemStatusResponse>("GET", path, query, undefined)
  }

  async listSlOs(): Promise<ListSlOsResponse> {
    let path = "/v1/slos"
    const query = new URLSearchParams()
    return this.requestJSON<ListSlOsResponse>("GET", path, query, undefined)
  }

  async exportOpenSlo(): Promise<ExportOpenSloResponse> {
    let path = "/v1/slos/openslo"
    const query = new URLSearchParams()
    return this.request("GET", path, query, undefined)
  }

  async listTests(request: ListTestsRequest = {}): Promise<ListTestsResponse> {
    let path = "/v1/tests"
    const query = new URLSearchParams()
    if (request.after !== undefined) query.set("after", String(request.after))
    if (request.limit !== undefined) query.set("limit", String(request.limit))
    return this.requestJSON<ListTestsResponse>("GET", path, query, undefined)
  }

  async createTest(request: CreateTestRequest): Promise<CreateTestResponse> {
    let path = "/v1/tests"
    const query = new URLSearchParams()
    if (request.q !== undefined) query.set("q", String(request.q))
    if (request.cause !== undefined) query.set("cause", String(request.cause))
    return this.requestJSON<CreateTestResponse>("POST", path, query, request.body)
  }

  async getTestBundle(): Promise<GetTestBundleResponse> {
    let path = "/v1/tests/bundle"
    const query = new URLSearchParams()
    return this.requestJSON<GetTestBundleResponse>("GET", path, query, undefined)
  }

  async getTest(): Promise<GetTestResponse> {
    let path = "/v1/tests/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<GetTestResponse>("GET", path, query, undefined)
  }

  async updateTest(request: UpdateTestRequest): Promise<UpdateTestResponse> {
    let path = "/v1/tests/{id}"
    const query = new URLSearchParams()
    return this.requestJSON<UpdateTestResponse>("PUT", path, query, request.body)
  }

  async deleteTest(): Promise<DeleteTestResponse> {
    let path = "/v1/tests/{id}"
    const query = new URLSearchParams()
    await this.request("DELETE", path, query, undefined)
  }

  async getTestPath(): Promise<GetTestPathResponse> {
    let path = "/v1/tests/{id}/path"
    const query = new URLSearchParams()
    return this.requestJSON<GetTestPathResponse>("GET", path, query, undefined)
  }

  async discoverTestPath(): Promise<DiscoverTestPathResponse> {
    let path = "/v1/tests/{id}/path"
    const query = new URLSearchParams()
    return this.requestJSON<DiscoverTestPathResponse>("POST", path, query, undefined)
  }

  async listThreatDetections(): Promise<ListThreatDetectionsResponse> {
    let path = "/v1/threat/detections"
    const query = new URLSearchParams()
    return this.requestJSON<ListThreatDetectionsResponse>("GET", path, query, undefined)
  }

  async getThreatIntelStatus(): Promise<GetThreatIntelStatusResponse> {
    let path = "/v1/threat/intel/status"
    const query = new URLSearchParams()
    return this.requestJSON<GetThreatIntelStatusResponse>("GET", path, query, undefined)
  }

  async listTlsPosture(): Promise<ListTlsPostureResponse> {
    let path = "/v1/tls/posture"
    const query = new URLSearchParams()
    return this.requestJSON<ListTlsPostureResponse>("GET", path, query, undefined)
  }

  async getTopology(request: GetTopologyRequest = {}): Promise<GetTopologyResponse> {
    let path = "/v1/topology"
    const query = new URLSearchParams()
    if (request.at !== undefined) query.set("at", String(request.at))
    return this.requestJSON<GetTopologyResponse>("GET", path, query, undefined)
  }

  async simulateWhatIf(request: SimulateWhatIfRequest): Promise<SimulateWhatIfResponse> {
    let path = "/v1/topology/whatif"
    const query = new URLSearchParams()
    return this.requestJSON<SimulateWhatIfResponse>("POST", path, query, request.body)
  }

  async getVersion(): Promise<GetVersionResponse> {
    let path = "/version"
    const query = new URLSearchParams()
    return this.requestJSON<GetVersionResponse>("GET", path, query, undefined)
  }

  private async requestJSON<T>(method: string, path: string, query: URLSearchParams, body: unknown | undefined): Promise<T> {
    const response = await this.request(method, path, query, body)
    if (response.status === 204) return undefined as T
    return (await response.json()) as T
  }

  private async request(method: string, path: string, query: URLSearchParams, body: unknown | undefined): Promise<Response> {
    const qs = query.toString()
    const headers: Record<string, string> = { Accept: 'application/json' }
    if (body !== undefined) headers['Content-Type'] = 'application/json'
    if (this.options.token) headers.Authorization = `Bearer ${this.options.token}`
    if (this.options.tenant) headers['X-Probectl-Tenant'] = this.options.tenant
    if (this.options.userAgent) headers['User-Agent'] = this.options.userAgent
    const response = await this.fetcher(`${this.baseUrl}${path}${qs ? `?${qs}` : ''}`, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    if (!response.ok) throw await toSDKError(response)
    return response
  }
}

export class SDKError extends Error {
  constructor(
    readonly status: number,
    readonly code: string | undefined,
    message: string,
  ) {
    super(message)
    this.name = 'SDKError'
  }
}

async function toSDKError(response: Response): Promise<SDKError> {
  let code: string | undefined
  let message = `${response.status} ${response.statusText}`
  try {
    const body = (await response.json()) as { error?: { code?: string; message?: string } }
    code = body.error?.code
    if (body.error?.message) message = body.error.message
  } catch {
    // Non-JSON error bodies keep the status text.
  }
  return new SDKError(response.status, code, message)
}
