// SPDX-License-Identifier: BUSL-1.1
//
// Use of this source code is governed by the Business Source License 1.1
// in the LICENSE file at the root of this repository; on its Change Date
// each version converts to the Mozilla Public License 2.0.

package cipolicy

import (
	"encoding/json"
	"regexp"
	"strings"
	"testing"
)

// TestWebLockHasNoNonOptionalPlatformBinaries (DPR-236): platform-specific
// binaries — @esbuild/<os>-<arch>, @rollup/rollup-<os>-<arch> and friends — must
// be marked optional in web/package-lock.json. A lock that lists them as REQUIRED
// tells npm to install a NetBSD arm64 binary on a linux/x64 builder, and npm 10
// (the version CI and deploy/docker/Dockerfile both use) refuses with
// EBADPLATFORM in about seven seconds.
//
// That is not hypothetical: it took down eleven of fourteen failing jobs at once
// — web, web-rendered-a11y, image-scan and all EIGHT build-images jobs, because
// the Dockerfile's web stage runs `npm ci` too. npm 11 on a developer's laptop
// writes the lock that way and installs from it happily, so the break is
// invisible until CI sees it.
//
// The rule is therefore checked here, where it costs nothing, needs no docker and
// runs on every commit. Regenerate the lock with scripts/web_npm.sh, which uses
// the pinned image's npm.
//
// This is deliberately ONE invariant, not a lock validator. Whether a lock is
// installable at all is npm's own tree resolution and is not derivable from the
// file — an earlier attempt to approximate it here passed the exact lock that
// broke CI, which is worse than no check. scripts/check_web_lock.sh does that
// part properly with `npm ci --dry-run` under the pinned npm, in 3 seconds, and
// the `web` job runs it.
func TestWebLockHasNoNonOptionalPlatformBinaries(t *testing.T) {
	raw := readRepoFile(t, "web", "package-lock.json")
	var lock struct {
		LockfileVersion int `json:"lockfileVersion"`
		Packages        map[string]struct {
			Version   string            `json:"version"`
			Optional  bool              `json:"optional"`
			OS        []string          `json:"os"`
			CPU       []string          `json:"cpu"`
			Engines   json.RawMessage   `json:"engines"`
			Deps      map[string]string `json:"dependencies"`
			Optional2 map[string]string `json:"optionalDependencies"`
		} `json:"packages"`
	}
	if err := json.Unmarshal([]byte(raw), &lock); err != nil {
		t.Fatalf("parse web/package-lock.json: %v", err)
	}
	if lock.LockfileVersion < 3 {
		t.Fatalf("lockfileVersion %d; want >= 3", lock.LockfileVersion)
	}
	if len(lock.Packages) < 100 {
		t.Fatalf("only %d packages in the lock; it is not the real one", len(lock.Packages))
	}

	// A node is platform-pinned when it declares os or cpu constraints. That is
	// npm's own definition of the thing that cannot be installed everywhere.
	var bad []string
	pinned := 0
	for name, p := range lock.Packages {
		if len(p.OS) == 0 && len(p.CPU) == 0 {
			continue
		}
		pinned++
		if !p.Optional {
			bad = append(bad, name+"@"+p.Version+" os="+strings.Join(p.OS, ",")+" cpu="+strings.Join(p.CPU, ","))
		}
	}
	if pinned == 0 {
		// Either npm stopped recording constraints or the lock is a stub; both
		// mean this guard is no longer looking at anything.
		t.Fatal("no platform-pinned packages found in the lock; the guard has stopped checking anything")
	}
	if len(bad) != 0 {
		t.Fatalf("%d of %d platform-pinned packages are NOT optional — npm 10 will fail with "+
			"EBADPLATFORM on a linux/x64 builder and take every image build with it. Regenerate with "+
			"scripts/web_npm.sh install --package-lock-only:\n  %s",
			len(bad), pinned, strings.Join(bad[:min(len(bad), 8)], "\n  "))
	}
}

// TestWebNodeImageMatchesTheDockerfile (DPR-236): scripts/web_npm.sh and
// scripts/check_web_lock.sh must name the SAME digest as deploy/docker/Dockerfile's
// web stage. They carry it as a literal because SUPPLY-002 requires a statically
// identifiable image operand, and a literal in three places is a drift risk — so
// the drift is what gets tested.
//
// It matters because the whole point of those scripts is that the image which
// builds the shipped bundle is the image that owns web/package-lock.json. If the
// Dockerfile moves to a node that ships a different npm and the scripts do not,
// the lock is generated by a tool no consumer uses and the EBADPLATFORM/EUSAGE
// split comes straight back.
func TestWebNodeImageMatchesTheDockerfile(t *testing.T) {
	digest := regexp.MustCompile(`node:[0-9]+-bookworm-slim@sha256:[0-9a-f]{64}`)

	dockerfile := readRepoFile(t, "deploy", "docker", "Dockerfile")
	version := regexp.MustCompile(`ARG NODE_VERSION=([0-9]+)`).FindStringSubmatch(dockerfile)
	sha := regexp.MustCompile(`bookworm-slim@sha256:([0-9a-f]{64})`).FindStringSubmatch(dockerfile)
	if version == nil || sha == nil {
		t.Fatal("deploy/docker/Dockerfile no longer declares ARG NODE_VERSION and a digest-pinned bookworm-slim web stage")
	}
	want := "node:" + version[1] + "-bookworm-slim@sha256:" + sha[1]

	for _, script := range []string{"web_npm.sh", "check_web_lock.sh"} {
		body := readRepoFile(t, "scripts", script)
		found := digest.FindAllString(body, -1)
		if len(found) == 0 {
			t.Errorf("scripts/%s names no digest-pinned node image", script)
			continue
		}
		for _, got := range found {
			if got != want {
				t.Errorf("scripts/%s pins %s but deploy/docker/Dockerfile's web stage is %s", script, got, want)
			}
		}
	}
}
