//go:build linux

// Command l4flow is the S19a eBPF feasibility-spike loader. It loads the CO-RE
// program in bpf/l4flow.bpf.c, attaches it to the inet_sock_set_state
// tracepoint, and prints TCP connections observed via a ring buffer.
//
// This is throwaway de-risking code (sprint S19a); it is NOT part of the netctl
// production build (separate module, absent from go.work, excluded from CI).
// It requires a BTF-enabled Linux kernel (>=5.8) and CAP_BPF (or root); it will
// not run on macOS, in most CI runners, or in an unprivileged container — which
// is precisely the limitation the spike documents. See README.md and
// ../../docs/ebpf-feasibility.md.
//
// Build: clang + libbpf headers + a generated vmlinux.h, then `make build`
// (runs bpf2go via `go generate`, then `go build`).
package main

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -target bpfel l4flow ./bpf/l4flow.bpf.c -- -I./bpf

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

// l4Event mirrors struct l4_event in bpf/l4flow.bpf.c (same field order/sizes,
// 36 bytes, no padding). Decoded little-endian (amd64/arm64 are LE).
type l4Event struct {
	PID      uint32
	Comm     [16]byte
	Saddr    [4]byte
	Daddr    [4]byte
	Sport    uint16
	Dport    uint16
	Family   uint16
	NewState uint8
	Pad      uint8
}

const hint = `
This is expected unless you are on a BTF-enabled Linux kernel (>=5.8) with
CAP_BPF (or root). It will NOT run on macOS, in most CI runners, or in an
unprivileged container — that limitation is the whole point of the S19a spike.
See ../../docs/ebpf-feasibility.md.`

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "l4flow spike: %v\n%s\n", err, hint)
		os.Exit(1)
	}
}

func run() error {
	// Remove the memlock rlimit so the kernel accepts our maps/programs.
	if err := rlimit.RemoveMemlock(); err != nil {
		return fmt.Errorf("remove memlock (need CAP_BPF/root): %w", err)
	}

	// loadL4flowObjects is generated by bpf2go (`make generate`). An "undefined"
	// error here means the bindings have not been generated yet.
	var objs l4flowObjects
	if err := loadL4flowObjects(&objs, nil); err != nil {
		return fmt.Errorf("load objects (need a BTF kernel + CAP_BPF): %w", err)
	}
	defer objs.Close()

	tp, err := link.Tracepoint("sock", "inet_sock_set_state", objs.HandleSetState, nil)
	if err != nil {
		return fmt.Errorf("attach tracepoint: %w", err)
	}
	defer tp.Close()

	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		return fmt.Errorf("open ring buffer: %w", err)
	}
	defer rd.Close()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-stop
		rd.Close()
	}()

	fmt.Println("S19a l4flow spike: watching TCP connections (Ctrl-C to stop)...")
	for {
		rec, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return nil
			}
			fmt.Fprintf(os.Stderr, "ring buffer read: %v\n", err)
			continue
		}

		var e l4Event
		if err := binary.Read(bytes.NewReader(rec.RawSample), binary.LittleEndian, &e); err != nil {
			fmt.Fprintf(os.Stderr, "decode: %v\n", err)
			continue
		}

		src := netip.AddrFrom4(e.Saddr)
		dst := netip.AddrFrom4(e.Daddr)
		fmt.Printf("pid=%-7d comm=%-16s %s:%d -> %s:%d\n",
			e.PID, nullTerm(e.Comm[:]), src, e.Sport, dst, e.Dport)
	}
}

func nullTerm(b []byte) string {
	if i := bytes.IndexByte(b, 0); i >= 0 {
		return string(b[:i])
	}
	return string(b)
}
