// SPDX-License-Identifier: LicenseRef-probectl-TBD
// Code generated by cmd/probectl-sdkgen from internal/control/openapi.json; DO NOT EDIT.

package sdk

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/imfeelingtheagi/probectl/internal/crypto"
)

type SDKError struct {
	StatusCode int
	Code       string
	Message    string
	Body       []byte
}

func (e *SDKError) Error() string {
	if e.Message != "" {
		if e.Code != "" {
			return fmt.Sprintf("%s (%s)", e.Message, e.Code)
		}
		return e.Message
	}
	return fmt.Sprintf("probectl API status %d", e.StatusCode)
}

type Client struct {
	BaseURL    string
	Token      string
	Tenant     string
	HTTPClient *http.Client
	UserAgent  string
}

type Option func(*Client)

func WithToken(token string) Option   { return func(c *Client) { c.Token = token } }
func WithTenant(tenant string) Option { return func(c *Client) { c.Tenant = tenant } }
func WithHTTPClient(hc *http.Client) Option {
	return func(c *Client) {
		if hc != nil {
			c.HTTPClient = hc
		}
	}
}
func WithUserAgent(userAgent string) Option { return func(c *Client) { c.UserAgent = userAgent } }

func NewClient(baseURL string, opts ...Option) *Client {
	if strings.TrimSpace(baseURL) == "" {
		baseURL = "http://localhost:8080"
	}
	c := &Client{BaseURL: strings.TrimRight(baseURL, "/"), HTTPClient: crypto.HardenedHTTPClient(15 * time.Second), UserAgent: "probectl-go-sdk"}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func String(v string) *string    { return &v }
func Int(v int) *int             { return &v }
func Bool(v bool) *bool          { return &v }
func Float64(v float64) *float64 { return &v }

// An ABAC policy evaluated after RBAC (deny-override).
type ABACPolicy struct {
	Effect     string            `json:"effect"`
	Enabled    bool              `json:"enabled,omitempty"`
	Id         string            `json:"id,omitempty"`
	Name       string            `json:"name,omitempty"`
	Permission string            `json:"permission"`
	Priority   int               `json:"priority,omitempty"`
	Resource   map[string]string `json:"resource,omitempty"`
	Subject    map[string]string `json:"subject,omitempty"`
}

type ABACPolicyList struct {
	Items []ABACPolicy `json:"items,omitempty"`
}

type AIAnswer struct {
	Confidence           string       `json:"confidence,omitempty"`
	Evidence             []AIEvidence `json:"evidence,omitempty"`
	Findings             []AIFinding  `json:"findings,omitempty"`
	Id                   string       `json:"id,omitempty"`
	InsufficientEvidence bool         `json:"insufficient_evidence,omitempty"`
	Model                string       `json:"model,omitempty"`
	Question             string       `json:"question,omitempty"`
	RootCause            string       `json:"root_cause,omitempty"`
	Tenant               string       `json:"tenant,omitempty"`
}

type AIAskRequest struct {
	Question string            `json:"question"`
	Subject  map[string]string `json:"subject,omitempty"`
}

type AICitation struct {
	EvidenceId string `json:"evidence_id,omitempty"`
}

type AIEvidence struct {
	Domain     string `json:"domain,omitempty"`
	Id         string `json:"id,omitempty"`
	OccurredAt string `json:"occurred_at,omitempty"`
	Plane      string `json:"plane,omitempty"`
	Ref        string `json:"ref,omitempty"`
	Severity   string `json:"severity,omitempty"`
	Summary    string `json:"summary,omitempty"`
	Title      string `json:"title,omitempty"`
}

type AIFeedbackRequest struct {
	AnswerId string `json:"answer_id"`
	Comment  string `json:"comment,omitempty"`
	Question string `json:"question,omitempty"`
	Rating   string `json:"rating"`
}

type AIFinding struct {
	Citations []AICitation `json:"citations,omitempty"`
	Statement string       `json:"statement,omitempty"`
}

type Agent struct {
	AgentVersion string   `json:"agent_version,omitempty"`
	Capabilities []string `json:"capabilities"`
	CreatedAt    string   `json:"created_at,omitempty"`
	Hostname     string   `json:"hostname,omitempty"`
	Id           string   `json:"id"`
	LastSeenAt   string   `json:"last_seen_at,omitempty"`
	Name         string   `json:"name"`
	RegisteredAt string   `json:"registered_at,omitempty"`
	SpiffeId     string   `json:"spiffe_id,omitempty"`
	Status       string   `json:"status"`
	TenantId     string   `json:"tenant_id"`
}

type AgentList struct {
	Items      []Agent `json:"items"`
	NextCursor string  `json:"next_cursor,omitempty"`
}

type AgentPatch struct {
	Name string `json:"name"`
}

type AlertChannelTestRequest struct {
	Channel  ChannelSpec `json:"channel"`
	Metric   string      `json:"metric,omitempty"`
	RuleName string      `json:"rule_name,omitempty"`
}

type AlertChannelTestResponse struct {
	Accepted bool   `json:"accepted"`
	Type     string `json:"type"`
}

type AlertList struct {
	Items []AlertRule `json:"items,omitempty"`
}

type AlertRequest struct {
	Channels        []ChannelSpec     `json:"channels,omitempty"`
	Comparison      string            `json:"comparison,omitempty"`
	Enabled         bool              `json:"enabled,omitempty"`
	ForN            int               `json:"for_n,omitempty"`
	Match           map[string]string `json:"match,omitempty"`
	Metric          string            `json:"metric"`
	Name            string            `json:"name"`
	RenotifySeconds int               `json:"renotify_seconds,omitempty"`
	Sensitivity     float64           `json:"sensitivity,omitempty"`
	Severity        string            `json:"severity,omitempty"`
	Threshold       float64           `json:"threshold,omitempty"`
	Type            string            `json:"type"`
	Window          int               `json:"window,omitempty"`
}

type AlertRule struct {
	Channels        []ChannelSpec     `json:"channels,omitempty"`
	Comparison      string            `json:"comparison,omitempty"`
	CreatedAt       string            `json:"created_at,omitempty"`
	Enabled         bool              `json:"enabled,omitempty"`
	ForN            int               `json:"for_n,omitempty"`
	Id              string            `json:"id,omitempty"`
	Match           map[string]string `json:"match,omitempty"`
	Metric          string            `json:"metric,omitempty"`
	Name            string            `json:"name,omitempty"`
	RenotifySeconds int               `json:"renotify_seconds,omitempty"`
	Sensitivity     float64           `json:"sensitivity,omitempty"`
	Severity        string            `json:"severity,omitempty"`
	TenantId        string            `json:"tenant_id,omitempty"`
	Threshold       float64           `json:"threshold,omitempty"`
	Type            string            `json:"type,omitempty"`
	UpdatedAt       string            `json:"updated_at,omitempty"`
	Window          int               `json:"window,omitempty"`
}

type AnomalyCitation struct {
	Metric string `json:"metric,omitempty"`
	Plane  string `json:"plane,omitempty"`
	Ref    string `json:"ref,omitempty"`
	Source string `json:"source,omitempty"`
}

type AnomalyTrainingWindow struct {
	End     string `json:"end,omitempty"`
	Samples int    `json:"samples,omitempty"`
	Start   string `json:"start,omitempty"`
}

// One record in the tenant's hash-chained, tamper-evident audit log. Privacy erasure is a projection: actor/target/data can be returned as erased tokens, while prev_hash/hash remain the raw-chain proof.
type AuditEvent struct {
	Action    string         `json:"action"`
	Actor     string         `json:"actor"`
	CreatedAt string         `json:"created_at,omitempty"`
	Data      map[string]any `json:"data,omitempty"`
	Hash      string         `json:"hash"`
	PrevHash  string         `json:"prev_hash,omitempty"`
	Seq       int            `json:"seq"`
	Target    string         `json:"target,omitempty"`
}

type AuditList struct {
	Items []AuditEvent `json:"items"`
	Next  int          `json:"next"`
}

type AuditVerify struct {
	Detail string `json:"detail,omitempty"`
	Ok     bool   `json:"ok"`
}

type AuthorRequest struct {
	Prompt string `json:"prompt"`
}

// A tenant-scoped BGP/routing signal projected from the incident timeline.
type BGPEvent struct {
	Attributes map[string]string `json:"attributes,omitempty"`
	Id         string            `json:"id,omitempty"`
	IncidentId string            `json:"incident_id,omitempty"`
	Kind       string            `json:"kind,omitempty"`
	OccurredAt string            `json:"occurred_at,omitempty"`
	Prefix     string            `json:"prefix,omitempty"`
	Severity   string            `json:"severity,omitempty"`
	Summary    string            `json:"summary,omitempty"`
	Target     string            `json:"target,omitempty"`
	Title      string            `json:"title,omitempty"`
}

type BGPEventList struct {
	BgpRunning     bool       `json:"bgp_running,omitempty"`
	EffectiveLimit int        `json:"effective_limit,omitempty"`
	Items          []BGPEvent `json:"items,omitempty"`
}

// A change scored as a candidate cause of an incident.
type ChangeCandidate struct {
	Event  ChangeEvent `json:"event,omitempty"`
	Reason string      `json:"reason,omitempty"`
	Score  float64     `json:"score,omitempty"`
}

type ChangeCandidateList struct {
	Items []ChangeCandidate `json:"items,omitempty"`
}

// A normalized change event ingested from a signed webhook (S29).
type ChangeEvent struct {
	Actor      string `json:"actor,omitempty"`
	Id         string `json:"id,omitempty"`
	Kind       string `json:"kind,omitempty"`
	OccurredAt string `json:"occurred_at,omitempty"`
	Prefix     string `json:"prefix,omitempty"`
	Ref        string `json:"ref,omitempty"`
	Source     string `json:"source,omitempty"`
	Summary    string `json:"summary,omitempty"`
	Target     string `json:"target,omitempty"`
	Title      string `json:"title,omitempty"`
	Url        string `json:"url,omitempty"`
}

type ChangeEventList struct {
	Items []ChangeEvent `json:"items,omitempty"`
}

type ChannelSpec struct {
	Recipients []string `json:"recipients,omitempty"`
	Secret     string   `json:"secret,omitempty"`
	Type       string   `json:"type"`
	Url        string   `json:"url,omitempty"`
}

type CollectorConfigHint struct {
	Env  map[string]string `json:"env"`
	Yaml map[string]string `json:"yaml"`
}

type CollectorRegisterRequest struct {
	Hostname string `json:"hostname,omitempty"`
	Plane    string `json:"plane"`
	Token    string `json:"token"`
}

type CollectorRegistration struct {
	AgentId      string              `json:"agent_id"`
	Capabilities []string            `json:"capabilities"`
	Config       CollectorConfigHint `json:"config"`
	Hostname     string              `json:"hostname,omitempty"`
	Plane        string              `json:"plane"`
	TenantId     string              `json:"tenant_id"`
}

// One managed network device visible in the tenant topology graph.
type DeviceInventory struct {
	Address   string            `json:"address,omitempty"`
	FirstSeen string            `json:"first_seen,omitempty"`
	Id        string            `json:"id,omitempty"`
	Labels    map[string]string `json:"labels,omitempty"`
	LastSeen  string            `json:"last_seen,omitempty"`
	Name      string            `json:"name,omitempty"`
}

type DeviceInventoryList struct {
	At              string            `json:"at,omitempty"`
	EffectiveLimit  int               `json:"effective_limit,omitempty"`
	Items           []DeviceInventory `json:"items,omitempty"`
	TopologyRunning bool              `json:"topology_running,omitempty"`
}

// Latest retained sample for one device/metric/interface series.
type DeviceMetricSummary struct {
	AgentId    string  `json:"agent_id,omitempty"`
	Device     string  `json:"device,omitempty"`
	DeviceName string  `json:"device_name,omitempty"`
	Id         string  `json:"id,omitempty"`
	IfIndex    string  `json:"if_index,omitempty"`
	IfName     string  `json:"if_name,omitempty"`
	LastSeen   string  `json:"last_seen,omitempty"`
	Metric     string  `json:"metric,omitempty"`
	Name       string  `json:"name,omitempty"`
	Source     string  `json:"source,omitempty"`
	Summary    string  `json:"summary,omitempty"`
	Value      float64 `json:"value,omitempty"`
}

type DeviceMetricSummaryList struct {
	EffectiveLimit int                   `json:"effective_limit,omitempty"`
	Items          []DeviceMetricSummary `json:"items,omitempty"`
	MetricsRunning bool                  `json:"metrics_running,omitempty"`
}

type DiscoverProposal struct {
	Rationale string   `json:"rationale,omitempty"`
	Score     int      `json:"score,omitempty"`
	Source    string   `json:"source,omitempty"`
	Spec      TestSpec `json:"spec,omitempty"`
}

type DiscoverProposalList struct {
	Proposals []DiscoverProposal `json:"proposals,omitempty"`
}

// One tenant-scoped eBPF host/L7 service edge aggregate.
type EBPFServiceEdge struct {
	AgentId         string `json:"agent_id,omitempty"`
	Bytes           int    `json:"bytes,omitempty"`
	Connections     int    `json:"connections,omitempty"`
	Destination     string `json:"destination,omitempty"`
	DestinationPort int    `json:"destination_port,omitempty"`
	Id              string `json:"id,omitempty"`
	L7Protocol      string `json:"l7_protocol,omitempty"`
	Name            string `json:"name,omitempty"`
	Packets         int    `json:"packets,omitempty"`
	Source          string `json:"source,omitempty"`
	Summary         string `json:"summary,omitempty"`
	WindowStart     string `json:"window_start,omitempty"`
}

type EBPFServiceMap struct {
	EbpfRunning    bool              `json:"ebpf_running,omitempty"`
	EffectiveLimit int               `json:"effective_limit,omitempty"`
	Items          []EBPFServiceEdge `json:"items,omitempty"`
	Source         string            `json:"source,omitempty"`
}

// The standard error envelope returned by every endpoint.
type Error struct {
	Error ErrorDetail `json:"error"`
}

type ErrorCode string

// The inner API error object. Code is stable and machine-readable; message is human-facing; request_id joins client output to server logs.
type ErrorDetail struct {
	Code      ErrorCode `json:"code"`
	Message   string    `json:"message"`
	RequestId string    `json:"request_id,omitempty"`
}

type FlowAnomaly struct {
	BaselineBps      float64               `json:"baseline_bps,omitempty"`
	CurrentBps       float64               `json:"current_bps,omitempty"`
	Exporter         string                `json:"exporter,omitempty"`
	FeatureCitations []AnomalyCitation     `json:"feature_citations,omitempty"`
	Features         map[string]float64    `json:"features,omitempty"`
	Iface            int                   `json:"iface,omitempty"`
	Model            string                `json:"model,omitempty"`
	Sigma            float64               `json:"sigma,omitempty"`
	StddevBps        float64               `json:"stddev_bps,omitempty"`
	TrainingWindow   AnomalyTrainingWindow `json:"training_window,omitempty"`
	Ts               string                `json:"ts,omitempty"`
}

type FlowAnomalyList struct {
	Items []FlowAnomaly `json:"items,omitempty"`
}

type FlowCapacityList struct {
	Items []FlowCapacityPoint `json:"items,omitempty"`
}

type FlowCapacityPoint struct {
	Bps      float64 `json:"bps,omitempty"`
	Exporter string  `json:"exporter,omitempty"`
	Iface    int     `json:"iface,omitempty"`
	Pps      float64 `json:"pps,omitempty"`
	Ts       string  `json:"ts,omitempty"`
}

type FlowTopList struct {
	EffectiveLimit int          `json:"effective_limit,omitempty"`
	Items          []FlowTopRow `json:"items,omitempty"`
	Window         string       `json:"window,omitempty"`
}

// One top-talkers row. key is the address/ASN per the grouping; detail carries the pair destination or AS organization name.
type FlowTopRow struct {
	Bytes   int    `json:"bytes,omitempty"`
	Detail  string `json:"detail,omitempty"`
	Flows   int    `json:"flows,omitempty"`
	Key     string `json:"key,omitempty"`
	Packets int    `json:"packets,omitempty"`
}

type Health struct {
	Status string `json:"status"`
}

type Hierarchy struct {
	Items []HierarchyOrganization `json:"items"`
}

type HierarchyCreate struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

type HierarchyOrganization struct {
	CreatedAt string          `json:"created_at"`
	Id        string          `json:"id"`
	Name      string          `json:"name"`
	Slug      string          `json:"slug"`
	Teams     []HierarchyTeam `json:"teams"`
	TenantId  string          `json:"tenant_id"`
	UpdatedAt string          `json:"updated_at"`
}

type HierarchyOrganizationFlat struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	TenantId  string `json:"tenant_id"`
	UpdatedAt string `json:"updated_at"`
}

type HierarchyProject struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	TeamId    string `json:"team_id"`
	TenantId  string `json:"tenant_id"`
	UpdatedAt string `json:"updated_at"`
}

type HierarchyTeam struct {
	CreatedAt string             `json:"created_at"`
	Id        string             `json:"id"`
	Name      string             `json:"name"`
	OrgId     string             `json:"org_id"`
	Projects  []HierarchyProject `json:"projects"`
	Slug      string             `json:"slug"`
	TenantId  string             `json:"tenant_id"`
	UpdatedAt string             `json:"updated_at"`
}

type HierarchyTeamFlat struct {
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Name      string `json:"name"`
	OrgId     string `json:"org_id"`
	Slug      string `json:"slug"`
	TenantId  string `json:"tenant_id"`
	UpdatedAt string `json:"updated_at"`
}

type Hop struct {
	Nodes []HopNode `json:"nodes"`
	Ttl   int       `json:"ttl"`
}

// One responder at a TTL; multiple nodes at a TTL are ECMP branches.
type HopNode struct {
	Ip        string      `json:"ip"`
	LossRatio float64     `json:"loss_ratio,omitempty"`
	Mpls      []MPLSLabel `json:"mpls,omitempty"`
	Received  int         `json:"received,omitempty"`
	RttAvgMs  float64     `json:"rtt_avg_ms,omitempty"`
	RttMaxMs  float64     `json:"rtt_max_ms,omitempty"`
	RttMinMs  float64     `json:"rtt_min_ms,omitempty"`
	Sent      int         `json:"sent,omitempty"`
}

type Incident struct {
	Id          string   `json:"id,omitempty"`
	LastSeenAt  string   `json:"last_seen_at,omitempty"`
	Prefix      string   `json:"prefix,omitempty"`
	ResolvedAt  string   `json:"resolved_at,omitempty"`
	Severity    string   `json:"severity,omitempty"`
	SignalCount int      `json:"signal_count,omitempty"`
	Signals     []Signal `json:"signals,omitempty"`
	StartedAt   string   `json:"started_at,omitempty"`
	Status      string   `json:"status,omitempty"`
	Target      string   `json:"target,omitempty"`
	TenantId    string   `json:"tenant_id,omitempty"`
	Title       string   `json:"title,omitempty"`
}

type IncidentList struct {
	Items []Incident `json:"items,omitempty"`
}

type IncidentPatch struct {
	Status string `json:"status"`
}

type InventorySavedView struct {
	CreatedAt string            `json:"created_at"`
	Filters   map[string]string `json:"filters"`
	Id        string            `json:"id"`
	Name      string            `json:"name"`
	Surface   string            `json:"surface"`
	TenantId  string            `json:"tenant_id"`
	UpdatedAt string            `json:"updated_at"`
}

type InventorySavedViewInput struct {
	Filters map[string]string `json:"filters,omitempty"`
	Name    string            `json:"name"`
	Surface string            `json:"surface"`
}

type InventorySavedViewList struct {
	Items []InventorySavedView `json:"items"`
}

type IsolationLaneStatus struct {
	Mode         string `json:"mode"`
	Namespace    string `json:"namespace,omitempty"`
	Strict       bool   `json:"strict"`
	TenantTagged bool   `json:"tenant_tagged"`
	TopicExample string `json:"topic_example"`
}

type IsolationRLSStatus struct {
	DatabaseConfigured bool   `json:"database_configured"`
	Detail             string `json:"detail"`
	Enforced           bool   `json:"enforced"`
	Healthy            bool   `json:"healthy"`
}

type IsolationRoutingStatus struct {
	ClickhouseDatabase                 string `json:"clickhouse_database,omitempty"`
	ClickhouseResidencyPlaneConfigured bool   `json:"clickhouse_residency_plane_configured"`
	Enabled                            bool   `json:"enabled"`
	Error                              string `json:"error,omitempty"`
	FailClosed                         bool   `json:"fail_closed"`
	ObjectPrefix                       string `json:"object_prefix,omitempty"`
	PgSchema                           string `json:"pg_schema,omitempty"`
	Resolved                           bool   `json:"resolved"`
}

type IsolationStatus struct {
	EffectiveModel string                 `json:"effective_model"`
	Id             string                 `json:"id"`
	LaneNamespace  IsolationLaneStatus    `json:"lane_namespace"`
	Name           string                 `json:"name"`
	RegistryModel  string                 `json:"registry_model"`
	Residency      string                 `json:"residency,omitempty"`
	Rls            IsolationRLSStatus     `json:"rls"`
	SiloRouting    IsolationRoutingStatus `json:"silo_routing"`
	Status         string                 `json:"status"`
	Summary        string                 `json:"summary"`
	TenantId       string                 `json:"tenant_id"`
}

type LifecycleRetentionInput struct {
	FlowRetentionDays *int `json:"flow_retention_days"`
}

type LifecycleStatus struct {
	FlowRetentionDays *int   `json:"flow_retention_days"`
	IsolationModel    string `json:"isolation_model"`
	Residency         string `json:"residency,omitempty"`
	TenantId          string `json:"tenant_id,omitempty"`
	UpdatedBy         string `json:"updated_by,omitempty"`
}

type Link struct {
	From string `json:"from,omitempty"`
	To   string `json:"to,omitempty"`
	Ttl  int    `json:"ttl,omitempty"`
}

type MPLSLabel struct {
	Label int  `json:"label,omitempty"`
	S     bool `json:"s,omitempty"`
	Tc    int  `json:"tc,omitempty"`
	Ttl   int  `json:"ttl,omitempty"`
}

// The authenticated caller: the resolved tenant (always present), identity, and the effective RBAC permission keys within that tenant.
type Me struct {
	DisplayName  string   `json:"display_name,omitempty"`
	Email        string   `json:"email,omitempty"`
	MfaSatisfied bool     `json:"mfa_satisfied,omitempty"`
	Permissions  []string `json:"permissions"`
	TenantId     string   `json:"tenant_id"`
	UserId       string   `json:"user_id"`
}

// Read-only, tenant-scoped on-call/ITSM posture. Secrets and endpoint path/query values are intentionally omitted.
type OncallStatus struct {
	Configured             bool             `json:"configured"`
	DispatcherRunning      bool             `json:"dispatcher_running"`
	Id                     string           `json:"id"`
	Inbound                []map[string]any `json:"inbound"`
	InboundConfigured      bool             `json:"inbound_configured"`
	InboundWebhookCount    int              `json:"inbound_webhook_count"`
	Name                   string           `json:"name"`
	Outbound               []map[string]any `json:"outbound"`
	OutboundConfigured     bool             `json:"outbound_configured"`
	OutboundConnectorCount int              `json:"outbound_connector_count"`
	Providers              []map[string]any `json:"providers"`
	SecretsRedacted        bool             `json:"secrets_redacted"`
	Summary                string           `json:"summary"`
	SupportedProviders     []string         `json:"supported_providers"`
	TlsRequired            bool             `json:"tls_required"`
}

type OncallTestRequest struct {
	ConnectorId string `json:"connector_id"`
}

type OncallTestResponse struct {
	Accepted    bool   `json:"accepted"`
	ConnectorId string `json:"connector_id"`
	ExternalRef string `json:"external_ref,omitempty"`
	Provider    string `json:"provider"`
	Status      string `json:"status,omitempty"`
}

// A merged, multi-path traceroute result.
type Path struct {
	DestinationReached bool   `json:"destination_reached,omitempty"`
	Hops               []Hop  `json:"hops"`
	Links              []Link `json:"links"`
	MaxHops            int    `json:"max_hops,omitempty"`
	Mode               string `json:"mode"`
	Target             string `json:"target"`
	TargetIp           string `json:"target_ip,omitempty"`
	TraceCount         int    `json:"trace_count,omitempty"`
}

// A SCIM bearer-token metadata row. The token hash and plaintext token are never returned from list/get responses.
type SCIMToken struct {
	CreatedAt  string `json:"created_at"`
	Id         string `json:"id"`
	LastUsedAt string `json:"last_used_at,omitempty"`
	Name       string `json:"name"`
	RevokedAt  string `json:"revoked_at,omitempty"`
	TenantId   string `json:"tenant_id"`
}

type SCIMTokenCreate struct {
	Name string `json:"name,omitempty"`
}

// The one-time SCIM bearer token response. The token value is never retrievable again.
type SCIMTokenCreated struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Token string `json:"token"`
}

type SCIMTokenList struct {
	Items []SCIMToken `json:"items,omitempty"`
}

// Read-only SIEM export posture. Endpoint path/query and ingest token are intentionally omitted.
type SIEMStatus struct {
	AuditPollInterval     string   `json:"audit_poll_interval"`
	BufferSize            int      `json:"buffer_size"`
	Configured            bool     `json:"configured"`
	Enabled               bool     `json:"enabled"`
	EndpointConfigured    bool     `json:"endpoint_configured"`
	EndpointHost          string   `json:"endpoint_host,omitempty"`
	EndpointTlsConfigured bool     `json:"endpoint_tls_configured"`
	Format                string   `json:"format"`
	Id                    string   `json:"id"`
	Name                  string   `json:"name"`
	NoDropDelivery        bool     `json:"no_drop_delivery"`
	Preset                string   `json:"preset"`
	Reason                string   `json:"reason,omitempty"`
	RedactKeyCount        int      `json:"redact_key_count"`
	SiemRunning           bool     `json:"siem_running"`
	Streams               []string `json:"streams"`
	Summary               string   `json:"summary"`
	TlsRequired           bool     `json:"tls_required"`
	TokenConfigured       bool     `json:"token_configured"`
}

// One plane's observation on an incident timeline (extensible: plane/kind are free-form, attributes is arbitrary).
type Signal struct {
	Attributes map[string]string `json:"attributes,omitempty"`
	Kind       string            `json:"kind,omitempty"`
	OccurredAt string            `json:"occurred_at,omitempty"`
	Plane      string            `json:"plane,omitempty"`
	Prefix     string            `json:"prefix,omitempty"`
	Severity   string            `json:"severity,omitempty"`
	Summary    string            `json:"summary,omitempty"`
	Target     string            `json:"target,omitempty"`
	Title      string            `json:"title,omitempty"`
}

type Test struct {
	CreatedAt       string            `json:"created_at"`
	Enabled         bool              `json:"enabled,omitempty"`
	Id              string            `json:"id"`
	IntervalSeconds int               `json:"interval_seconds,omitempty"`
	Name            string            `json:"name"`
	Params          map[string]string `json:"params,omitempty"`
	Target          string            `json:"target,omitempty"`
	TenantId        string            `json:"tenant_id"`
	TimeoutSeconds  int               `json:"timeout_seconds,omitempty"`
	Type            string            `json:"type"`
	UpdatedAt       string            `json:"updated_at"`
}

type TestList struct {
	Items      []Test `json:"items"`
	NextCursor string `json:"next_cursor,omitempty"`
}

type TestProposal struct {
	Rationale string   `json:"rationale,omitempty"`
	Source    string   `json:"source,omitempty"`
	Spec      TestSpec `json:"spec,omitempty"`
}

// The mutable fields of a synthetic test.
type TestRequest struct {
	Enabled         bool              `json:"enabled,omitempty"`
	IntervalSeconds int               `json:"interval_seconds,omitempty"`
	Name            string            `json:"name"`
	Params          map[string]string `json:"params,omitempty"`
	Target          string            `json:"target,omitempty"`
	TimeoutSeconds  int               `json:"timeout_seconds,omitempty"`
	Type            string            `json:"type"`
}

type TestSpec struct {
	Enabled         bool              `json:"enabled,omitempty"`
	IntervalSeconds int               `json:"interval_seconds,omitempty"`
	Name            string            `json:"name,omitempty"`
	Params          map[string]string `json:"params,omitempty"`
	Target          string            `json:"target,omitempty"`
	TimeoutSeconds  int               `json:"timeout_seconds,omitempty"`
	Type            string            `json:"type,omitempty"`
}

type Version struct {
	Arch      string `json:"arch"`
	Commit    string `json:"commit"`
	Date      string `json:"date"`
	GoVersion string `json:"go_version"`
	Os        string `json:"os"`
	Version   string `json:"version"`
}

// OIDC redirect URI: completes login and sets the session cookie
type SsoCallbackRequest struct {
	Code  *string `json:"-"`
	State *string `json:"-"`
}

func (c *Client) SsoCallback(ctx context.Context, req SsoCallbackRequest) error {
	path := "/auth/callback"
	query := url.Values{}
	if req.Code != nil {
		query.Set("code", formatQueryValue(*req.Code))
	}
	if req.State != nil {
		query.Set("state", formatQueryValue(*req.State))
	}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Begin OIDC SSO login (redirects to the tenant's identity provider)
type SsoLoginRequest struct {
	Tenant *string `json:"-"`
}

func (c *Client) SsoLogin(ctx context.Context, req SsoLoginRequest) error {
	path := "/auth/login"
	query := url.Values{}
	if req.Tenant != nil {
		query.Set("tenant", formatQueryValue(*req.Tenant))
	}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Revoke the current session and clear the session cookie
type SsoLogoutRequest struct {
}

func (c *Client) SsoLogout(ctx context.Context, req SsoLogoutRequest) error {
	path := "/auth/logout"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Agent bootstrap: redeem a single-use join token for a tenant-bound SVID (pre-identity; token-authenticated; per-IP throttled)
type AgentEnrollRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) AgentEnroll(ctx context.Context, req AgentEnrollRequest) error {
	path := "/enroll/agent"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, req.Body, nil)
}

// Rotate an agent SVID over proof of the current identity (chain + key possession); identity never changes
type AgentRotateRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) AgentRotate(ctx context.Context, req AgentRotateRequest) error {
	path := "/enroll/agent/rotate"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, req.Body, nil)
}

// Liveness probe
type GetHealthzRequest struct {
}

func (c *Client) GetHealthz(ctx context.Context, req GetHealthzRequest) (*Health, error) {
	path := "/healthz"
	query := url.Values{}
	var out Health
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// RUM beacon ingest (S47b) — public-key routed
type IngestRumBeaconRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) IngestRumBeacon(ctx context.Context, req IngestRumBeaconRequest) (map[string]any, error) {
	path := "/ingest/rum"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// This OpenAPI 3.1 document
type GetOpenApiRequest struct {
}

func (c *Client) GetOpenApi(ctx context.Context, req GetOpenApiRequest) error {
	path := "/openapi.json"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Readiness probe
type GetReadyzRequest struct {
}

func (c *Client) GetReadyz(ctx context.Context, req GetReadyzRequest) (*Health, error) {
	path := "/readyz"
	query := url.Values{}
	var out Health
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Start a tenant-scoped agent-to-agent site mesh
type StartA2aMeshRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) StartA2aMesh(ctx context.Context, req StartA2aMeshRequest) (map[string]any, error) {
	path := "/v1/a2a/mesh"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Start a brokered agent-to-agent measurement session
type StartA2aSessionRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) StartA2aSession(ctx context.Context, req StartA2aSessionRequest) (map[string]any, error) {
	path := "/v1/a2a/sessions"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List ABAC policies
type ListPoliciesRequest struct {
}

func (c *Client) ListPolicies(ctx context.Context, req ListPoliciesRequest) (*ABACPolicyList, error) {
	path := "/v1/abac/policies"
	query := url.Values{}
	var out ABACPolicyList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create an ABAC policy
type CreatePolicyRequest struct {
	Body *ABACPolicy `json:"-"`
}

func (c *Client) CreatePolicy(ctx context.Context, req CreatePolicyRequest) (*ABACPolicy, error) {
	path := "/v1/abac/policies"
	query := url.Values{}
	var out ABACPolicy
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete an ABAC policy
type DeletePolicyRequest struct {
}

func (c *Client) DeletePolicy(ctx context.Context, req DeletePolicyRequest) error {
	path := "/v1/abac/policies/{id}"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// List agents
type ListAgentsRequest struct {
	After *string `json:"-"`
	Limit *int    `json:"-"`
}

func (c *Client) ListAgents(ctx context.Context, req ListAgentsRequest) (*AgentList, error) {
	path := "/v1/agents"
	query := url.Values{}
	if req.After != nil {
		query.Set("after", formatQueryValue(*req.After))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out AgentList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Mint a one-time, tenant-scoped agent enrollment token (admin; audited; shown once)
type MintAgentEnrollTokenRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) MintAgentEnrollToken(ctx context.Context, req MintAgentEnrollTokenRequest) (map[string]any, error) {
	path := "/v1/agents/enroll-tokens"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Get an agent
type GetAgentRequest struct {
}

func (c *Client) GetAgent(ctx context.Context, req GetAgentRequest) (*Agent, error) {
	path := "/v1/agents/{id}"
	query := url.Values{}
	var out Agent
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update an agent's display name
type PatchAgentRequest struct {
	Body *AgentPatch `json:"-"`
}

func (c *Client) PatchAgent(ctx context.Context, req PatchAgentRequest) (*Agent, error) {
	path := "/v1/agents/{id}"
	query := url.Values{}
	var out Agent
	if err := c.doJSON(ctx, http.MethodPatch, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Deregister an agent (deprecated legacy metadata delete)
type DeleteAgentRequest struct {
}

func (c *Client) DeleteAgent(ctx context.Context, req DeleteAgentRequest) error {
	path := "/v1/agents/{id}"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// CMDB CI correlated to an agent (by hostname)
type AgentCiRequest struct {
	Id string `json:"-"`
}

func (c *Client) AgentCi(ctx context.Context, req AgentCiRequest) (map[string]any, error) {
	path := "/v1/agents/{id}/ci"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Revoke an agent's identity (WIRE-003): persists, blocks re-enrollment/rotation, and refuses its mTLS handshakes from the next connection
type RevokeAgentRequest struct {
	Id string `json:"-"`
}

func (c *Client) RevokeAgent(ctx context.Context, req RevokeAgentRequest) error {
	path := "/v1/agents/{id}/revoke"
	if req.Id == "" {
		return fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Ask the AI assistant (cited, RBAC-scoped root-cause analysis)
type AiAskRequest struct {
	Body *AIAskRequest `json:"-"`
}

func (c *Client) AiAsk(ctx context.Context, req AiAskRequest) (*AIAnswer, error) {
	path := "/v1/ai/ask"
	query := url.Values{}
	var out AIAnswer
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Author a test config from a natural-language request (schema-validated, pending confirmation)
type AiAuthorRequest struct {
	Body *AuthorRequest `json:"-"`
}

func (c *Client) AiAuthor(ctx context.Context, req AiAuthorRequest) (*TestProposal, error) {
	path := "/v1/ai/author"
	query := url.Values{}
	var out TestProposal
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Propose monitorable targets mined from observed telemetry (ranked, deduped; pending confirmation)
type AiDiscoverRequest struct {
}

func (c *Client) AiDiscover(ctx context.Context, req AiDiscoverRequest) (*DiscoverProposalList, error) {
	path := "/v1/ai/discover"
	query := url.Values{}
	var out DiscoverProposalList
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Submit feedback (thumbs up/down) on an AI answer
type AiFeedbackRequest struct {
	Body *AIFeedbackRequest `json:"-"`
}

func (c *Client) AiFeedback(ctx context.Context, req AiFeedbackRequest) error {
	path := "/v1/ai/feedback"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, req.Body, nil)
}

// List alert rules
type ListAlertsRequest struct {
}

func (c *Client) ListAlerts(ctx context.Context, req ListAlertsRequest) (*AlertList, error) {
	path := "/v1/alerts"
	query := url.Values{}
	var out AlertList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create an alert rule
type CreateAlertRequest struct {
	Body *AlertRequest `json:"-"`
}

func (c *Client) CreateAlert(ctx context.Context, req CreateAlertRequest) (*AlertRule, error) {
	path := "/v1/alerts"
	query := url.Values{}
	var out AlertRule
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Firing alerts (engine truth) with silence/ack state
type ListActiveAlertsRequest struct {
}

func (c *Client) ListActiveAlerts(ctx context.Context, req ListActiveAlertsRequest) (map[string]any, error) {
	path := "/v1/alerts/active"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Acknowledge a firing alert (records who owns it)
type AcknowledgeAlertRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) AcknowledgeAlert(ctx context.Context, req AcknowledgeAlertRequest) (map[string]any, error) {
	path := "/v1/alerts/active/ack"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Silence a firing alert's notifications until a deadline
type SilenceAlertRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) SilenceAlert(ctx context.Context, req SilenceAlertRequest) (map[string]any, error) {
	path := "/v1/alerts/active/silence"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List reusable planned-maintenance windows
type ListMaintenanceWindowsRequest struct {
}

func (c *Client) ListMaintenanceWindows(ctx context.Context, req ListMaintenanceWindowsRequest) (map[string]any, error) {
	path := "/v1/alerts/maintenance"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Create or update a planned-maintenance window
type UpsertMaintenanceWindowRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) UpsertMaintenanceWindow(ctx context.Context, req UpsertMaintenanceWindowRequest) (map[string]any, error) {
	path := "/v1/alerts/maintenance"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Preview planned-maintenance occurrences
type PreviewMaintenanceWindowsRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) PreviewMaintenanceWindows(ctx context.Context, req PreviewMaintenanceWindowsRequest) (map[string]any, error) {
	path := "/v1/alerts/maintenance/preview"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Delete a planned-maintenance window
type DeleteMaintenanceWindowRequest struct {
	Id string `json:"-"`
}

func (c *Client) DeleteMaintenanceWindow(ctx context.Context, req DeleteMaintenanceWindowRequest) error {
	path := "/v1/alerts/maintenance/{id}"
	if req.Id == "" {
		return fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// Send a test alert delivery to a supplied channel
type TestAlertChannelRequest struct {
	Body *AlertChannelTestRequest `json:"-"`
}

func (c *Client) TestAlertChannel(ctx context.Context, req TestAlertChannelRequest) (*AlertChannelTestResponse, error) {
	path := "/v1/alerts/test-channel"
	query := url.Values{}
	var out AlertChannelTestResponse
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get an alert rule
type GetAlertRequest struct {
}

func (c *Client) GetAlert(ctx context.Context, req GetAlertRequest) (*AlertRule, error) {
	path := "/v1/alerts/{id}"
	query := url.Values{}
	var out AlertRule
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update an alert rule
type UpdateAlertRequest struct {
	Body *AlertRequest `json:"-"`
}

func (c *Client) UpdateAlert(ctx context.Context, req UpdateAlertRequest) (*AlertRule, error) {
	path := "/v1/alerts/{id}"
	query := url.Values{}
	var out AlertRule
	if err := c.doJSON(ctx, http.MethodPut, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete an alert rule
type DeleteAlertRequest struct {
}

func (c *Client) DeleteAlert(ctx context.Context, req DeleteAlertRequest) error {
	path := "/v1/alerts/{id}"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// Read a page of the tenant's tamper-evident audit trail
type ListAuditRequest struct {
	After  *int    `json:"-"`
	Limit  *int    `json:"-"`
	Actor  *string `json:"-"`
	Action *string `json:"-"`
	Target *string `json:"-"`
}

func (c *Client) ListAudit(ctx context.Context, req ListAuditRequest) (*AuditList, error) {
	path := "/v1/audit"
	query := url.Values{}
	if req.After != nil {
		query.Set("after", formatQueryValue(*req.After))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	if req.Actor != nil {
		query.Set("actor", formatQueryValue(*req.Actor))
	}
	if req.Action != nil {
		query.Set("action", formatQueryValue(*req.Action))
	}
	if req.Target != nil {
		query.Set("target", formatQueryValue(*req.Target))
	}
	var out AuditList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Verify the integrity of the tenant's audit chain
type VerifyAuditRequest struct {
}

func (c *Client) VerifyAudit(ctx context.Context, req VerifyAuditRequest) (*AuditVerify, error) {
	path := "/v1/audit/verify"
	query := url.Values{}
	var out AuditVerify
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List recent BGP/routing events
type ListBgpEventsRequest struct {
	Prefix *string `json:"-"`
	Asn    *string `json:"-"`
	Limit  *int    `json:"-"`
}

func (c *Client) ListBgpEvents(ctx context.Context, req ListBgpEventsRequest) (*BGPEventList, error) {
	path := "/v1/bgp/events"
	query := url.Values{}
	if req.Prefix != nil {
		query.Set("prefix", formatQueryValue(*req.Prefix))
	}
	if req.Asn != nil {
		query.Set("asn", formatQueryValue(*req.Asn))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out BGPEventList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Network energy/carbon estimate (S48)
type GetCarbonRequest struct {
}

func (c *Client) GetCarbon(ctx context.Context, req GetCarbonRequest) (map[string]any, error) {
	path := "/v1/carbon"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List change events (the change timeline)
type ListChangesRequest struct {
}

func (c *Client) ListChanges(ctx context.Context, req ListChangesRequest) (*ChangeEventList, error) {
	path := "/v1/changes"
	query := url.Values{}
	var out ChangeEventList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Look up CMDB CIs by IP address or hostname
type CmdbLookupRequest struct {
	Key *string `json:"-"`
}

func (c *Client) CmdbLookup(ctx context.Context, req CmdbLookupRequest) (map[string]any, error) {
	path := "/v1/cmdb/lookup"
	query := url.Values{}
	if req.Key != nil {
		query.Set("key", formatQueryValue(*req.Key))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Register a tenant-scoped bus collector from a one-time enrollment token
type RegisterCollectorRequest struct {
	Body *CollectorRegisterRequest `json:"-"`
}

func (c *Client) RegisterCollector(ctx context.Context, req RegisterCollectorRequest) (*CollectorRegistration, error) {
	path := "/v1/collectors/register"
	query := url.Values{}
	var out CollectorRegistration
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Segmentation validation results (S46)
type ListComplianceResultsRequest struct {
}

func (c *Client) ListComplianceResults(ctx context.Context, req ListComplianceResultsRequest) (map[string]any, error) {
	path := "/v1/compliance"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Audit-grade compliance evidence export (S46)
type ExportComplianceEvidenceRequest struct {
}

func (c *Client) ExportComplianceEvidence(ctx context.Context, req ExportComplianceEvidenceRequest) (map[string]any, error) {
	path := "/v1/compliance/evidence"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// FinOps egress-cost summary (S44)
type GetCostSummaryRequest struct {
}

func (c *Client) GetCostSummary(ctx context.Context, req GetCostSummaryRequest) (map[string]any, error) {
	path := "/v1/cost/summary"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List latest device metric summaries
type ListDeviceMetricSummariesRequest struct {
	Device *string `json:"-"`
	Metric *string `json:"-"`
	Limit  *int    `json:"-"`
}

func (c *Client) ListDeviceMetricSummaries(ctx context.Context, req ListDeviceMetricSummariesRequest) (*DeviceMetricSummaryList, error) {
	path := "/v1/device/metrics"
	query := url.Values{}
	if req.Device != nil {
		query.Set("device", formatQueryValue(*req.Device))
	}
	if req.Metric != nil {
		query.Set("metric", formatQueryValue(*req.Metric))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out DeviceMetricSummaryList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List topology-visible managed devices
type ListDevicesRequest struct {
	Limit *int `json:"-"`
}

func (c *Client) ListDevices(ctx context.Context, req ListDevicesRequest) (*DeviceInventoryList, error) {
	path := "/v1/devices"
	query := url.Values{}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out DeviceInventoryList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Deep health report (S-EE4): per-component status (database, secrets resolver, cluster, license) aggregated to the worst — admin diagnostics.read
type GetV1DiagnosticsRequest struct {
}

func (c *Client) GetV1Diagnostics(ctx context.Context, req GetV1DiagnosticsRequest) error {
	path := "/v1/diagnostics"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Secret-stripped support bundle (S-EE4): tar.gz of versions, redacted config, deep health, self-metrics, anonymized topology, runtime — NO secrets/PII (guardrail 6); admin diagnostics.read
type GetV1DiagnosticsBundleRequest struct {
}

func (c *Client) GetV1DiagnosticsBundle(ctx context.Context, req GetV1DiagnosticsBundleRequest) error {
	path := "/v1/diagnostics/bundle"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// List SCIM bearer-token metadata
type ListScimTokensRequest struct {
}

func (c *Client) ListScimTokens(ctx context.Context, req ListScimTokensRequest) (*SCIMTokenList, error) {
	path := "/v1/directory/scim-tokens"
	query := url.Values{}
	var out SCIMTokenList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a SCIM bearer token
type CreateScimTokenRequest struct {
	Body *SCIMTokenCreate `json:"-"`
}

func (c *Client) CreateScimToken(ctx context.Context, req CreateScimTokenRequest) (*SCIMTokenCreated, error) {
	path := "/v1/directory/scim-tokens"
	query := url.Values{}
	var out SCIMTokenCreated
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Revoke a SCIM bearer token
type RevokeScimTokenRequest struct {
}

func (c *Client) RevokeScimToken(ctx context.Context, req RevokeScimTokenRequest) error {
	path := "/v1/directory/scim-tokens/{id}"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// List eBPF host/L7 service edges
type ListEbpfServiceMapRequest struct {
	Source *string `json:"-"`
	Since  *string `json:"-"`
	Until  *string `json:"-"`
	Limit  *int    `json:"-"`
}

func (c *Client) ListEbpfServiceMap(ctx context.Context, req ListEbpfServiceMapRequest) (*EBPFServiceMap, error) {
	path := "/v1/ebpf/service-map"
	query := url.Values{}
	if req.Source != nil {
		query.Set("source", formatQueryValue(*req.Source))
	}
	if req.Since != nil {
		query.Set("since", formatQueryValue(*req.Since))
	}
	if req.Until != nil {
		query.Set("until", formatQueryValue(*req.Until))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out EBPFServiceMap
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Editions / license state (S-T0)
type GetEditionsRequest struct {
}

func (c *Client) GetEditions(ctx context.Context, req GetEditionsRequest) (map[string]any, error) {
	path := "/v1/editions"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Endpoint DEM fleet: WiFi/gateway/last-mile health + slowdown attribution
type ListEndpointsRequest struct {
}

func (c *Client) ListEndpoints(ctx context.Context, req ListEndpointsRequest) (map[string]any, error) {
	path := "/v1/endpoints"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// The tenant's own fairness view (S-T7): the bounds it runs under (policy) + admitted/shed/rejected accounting — debugging a fairness dispute never requires the provider's word
type GetV1FairnessRequest struct {
}

func (c *Client) GetV1Fairness(ctx context.Context, req GetV1FairnessRequest) error {
	path := "/v1/fairness"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Interfaces whose latest bucket departs from their own baseline
type FlowAnomaliesRequest struct {
	Exporter  *string  `json:"-"`
	Direction *string  `json:"-"`
	Window    *string  `json:"-"`
	Bucket    *string  `json:"-"`
	K         *float64 `json:"-"`
	MinBps    *float64 `json:"-"`
}

func (c *Client) FlowAnomalies(ctx context.Context, req FlowAnomaliesRequest) (*FlowAnomalyList, error) {
	path := "/v1/flows/anomalies"
	query := url.Values{}
	if req.Exporter != nil {
		query.Set("exporter", formatQueryValue(*req.Exporter))
	}
	if req.Direction != nil {
		query.Set("direction", formatQueryValue(*req.Direction))
	}
	if req.Window != nil {
		query.Set("window", formatQueryValue(*req.Window))
	}
	if req.Bucket != nil {
		query.Set("bucket", formatQueryValue(*req.Bucket))
	}
	if req.K != nil {
		query.Set("k", formatQueryValue(*req.K))
	}
	if req.MinBps != nil {
		query.Set("min_bps", formatQueryValue(*req.MinBps))
	}
	var out FlowAnomalyList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Per-exporter/interface throughput buckets (capacity view)
type FlowCapacityRequest struct {
	Exporter  *string `json:"-"`
	Direction *string `json:"-"`
	Window    *string `json:"-"`
	Bucket    *string `json:"-"`
}

func (c *Client) FlowCapacity(ctx context.Context, req FlowCapacityRequest) (*FlowCapacityList, error) {
	path := "/v1/flows/capacity"
	query := url.Values{}
	if req.Exporter != nil {
		query.Set("exporter", formatQueryValue(*req.Exporter))
	}
	if req.Direction != nil {
		query.Set("direction", formatQueryValue(*req.Direction))
	}
	if req.Window != nil {
		query.Set("window", formatQueryValue(*req.Window))
	}
	if req.Bucket != nil {
		query.Set("bucket", formatQueryValue(*req.Bucket))
	}
	var out FlowCapacityList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Top talkers from the flow plane (sampling-corrected)
type FlowTopTalkersRequest struct {
	By     *string `json:"-"`
	Window *string `json:"-"`
	Limit  *int    `json:"-"`
}

func (c *Client) FlowTopTalkers(ctx context.Context, req FlowTopTalkersRequest) (*FlowTopList, error) {
	path := "/v1/flows/top"
	query := url.Values{}
	if req.By != nil {
		query.Set("by", formatQueryValue(*req.By))
	}
	if req.Window != nil {
		query.Set("window", formatQueryValue(*req.Window))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out FlowTopList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Label values
type PromLabelValuesRequest struct {
	Name  string  `json:"-"`
	Match *string `json:"-"`
	Start *string `json:"-"`
	End   *string `json:"-"`
}

func (c *Client) PromLabelValues(ctx context.Context, req PromLabelValuesRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/label/{name}/values"
	if req.Name == "" {
		return nil, fmt.Errorf("name is required")
	}
	path = strings.ReplaceAll(path, "{name}", url.PathEscape(req.Name))
	query := url.Values{}
	if req.Match != nil {
		query.Set("match[]", formatQueryValue(*req.Match))
	}
	if req.Start != nil {
		query.Set("start", formatQueryValue(*req.Start))
	}
	if req.End != nil {
		query.Set("end", formatQueryValue(*req.End))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Label names
type PromLabelsRequest struct {
	Match *string `json:"-"`
	Start *string `json:"-"`
	End   *string `json:"-"`
}

func (c *Client) PromLabels(ctx context.Context, req PromLabelsRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/labels"
	query := url.Values{}
	if req.Match != nil {
		query.Set("match[]", formatQueryValue(*req.Match))
	}
	if req.Start != nil {
		query.Set("start", formatQueryValue(*req.Start))
	}
	if req.End != nil {
		query.Set("end", formatQueryValue(*req.End))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Label names (form-encoded)
type PromLabelsFormRequest struct {
}

func (c *Client) PromLabelsForm(ctx context.Context, req PromLabelsFormRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/labels"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Metric metadata (empty; probectl serves none yet)
type PromMetadataRequest struct {
}

func (c *Client) PromMetadata(ctx context.Context, req PromMetadataRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/metadata"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Instant query (Grafana datasource)
type PromQueryRequest struct {
	Query *string `json:"-"`
	Time  *string `json:"-"`
}

func (c *Client) PromQuery(ctx context.Context, req PromQueryRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/query"
	query := url.Values{}
	if req.Query != nil {
		query.Set("query", formatQueryValue(*req.Query))
	}
	if req.Time != nil {
		query.Set("time", formatQueryValue(*req.Time))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Instant query (form-encoded, as Grafana sends it)
type PromQueryFormRequest struct {
}

func (c *Client) PromQueryForm(ctx context.Context, req PromQueryFormRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/query"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Range query (Grafana datasource)
type PromQueryRangeRequest struct {
	Query *string `json:"-"`
	Start *string `json:"-"`
	End   *string `json:"-"`
	Step  *string `json:"-"`
}

func (c *Client) PromQueryRange(ctx context.Context, req PromQueryRangeRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/query_range"
	query := url.Values{}
	if req.Query != nil {
		query.Set("query", formatQueryValue(*req.Query))
	}
	if req.Start != nil {
		query.Set("start", formatQueryValue(*req.Start))
	}
	if req.End != nil {
		query.Set("end", formatQueryValue(*req.End))
	}
	if req.Step != nil {
		query.Set("step", formatQueryValue(*req.Step))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Range query (form-encoded, as Grafana sends it)
type PromQueryRangeFormRequest struct {
}

func (c *Client) PromQueryRangeForm(ctx context.Context, req PromQueryRangeFormRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/query_range"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Series metadata
type PromSeriesRequest struct {
	Match *string `json:"-"`
	Start *string `json:"-"`
	End   *string `json:"-"`
}

func (c *Client) PromSeries(ctx context.Context, req PromSeriesRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/series"
	query := url.Values{}
	if req.Match != nil {
		query.Set("match[]", formatQueryValue(*req.Match))
	}
	if req.Start != nil {
		query.Set("start", formatQueryValue(*req.Start))
	}
	if req.End != nil {
		query.Set("end", formatQueryValue(*req.End))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Series metadata (form-encoded)
type PromSeriesFormRequest struct {
}

func (c *Client) PromSeriesForm(ctx context.Context, req PromSeriesFormRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/series"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Prometheus API compatibility level (Grafana capability probe)
type PromBuildInfoRequest struct {
}

func (c *Client) PromBuildInfo(ctx context.Context, req PromBuildInfoRequest) (map[string]any, error) {
	path := "/v1/grafana/api/v1/status/buildinfo"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Get the tenant org/team/project hierarchy
type GetHierarchyRequest struct {
}

func (c *Client) GetHierarchy(ctx context.Context, req GetHierarchyRequest) (*Hierarchy, error) {
	path := "/v1/hierarchy"
	query := url.Values{}
	var out Hierarchy
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create an organization in the caller tenant
type CreateHierarchyOrganizationRequest struct {
	Body *HierarchyCreate `json:"-"`
}

func (c *Client) CreateHierarchyOrganization(ctx context.Context, req CreateHierarchyOrganizationRequest) (*HierarchyOrganizationFlat, error) {
	path := "/v1/hierarchy/orgs"
	query := url.Values{}
	var out HierarchyOrganizationFlat
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a team under an organization
type CreateHierarchyTeamRequest struct {
	Id   string           `json:"-"`
	Body *HierarchyCreate `json:"-"`
}

func (c *Client) CreateHierarchyTeam(ctx context.Context, req CreateHierarchyTeamRequest) (*HierarchyTeamFlat, error) {
	path := "/v1/hierarchy/orgs/{id}/teams"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out HierarchyTeamFlat
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a project under a team
type CreateHierarchyProjectRequest struct {
	Id   string           `json:"-"`
	Body *HierarchyCreate `json:"-"`
}

func (c *Client) CreateHierarchyProject(ctx context.Context, req CreateHierarchyProjectRequest) (*HierarchyProject, error) {
	path := "/v1/hierarchy/teams/{id}/projects"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out HierarchyProject
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List incidents
type ListIncidentsRequest struct {
}

func (c *Client) ListIncidents(ctx context.Context, req ListIncidentsRequest) (*IncidentList, error) {
	path := "/v1/incidents"
	query := url.Values{}
	var out IncidentList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get an incident with its signal timeline
type GetIncidentRequest struct {
}

func (c *Client) GetIncident(ctx context.Context, req GetIncidentRequest) (*Incident, error) {
	path := "/v1/incidents/{id}"
	query := url.Values{}
	var out Incident
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Resolve an incident
type PatchIncidentRequest struct {
	Body *IncidentPatch `json:"-"`
}

func (c *Client) PatchIncident(ctx context.Context, req PatchIncidentRequest) (*Incident, error) {
	path := "/v1/incidents/{id}"
	query := url.Values{}
	var out Incident
	if err := c.doJSON(ctx, http.MethodPatch, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List changes correlated to an incident (candidate causes)
type ListIncidentChangesRequest struct {
}

func (c *Client) ListIncidentChanges(ctx context.Context, req ListIncidentChangesRequest) (*ChangeCandidateList, error) {
	path := "/v1/incidents/{id}/changes"
	query := url.Values{}
	var out ChangeCandidateList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// CMDB CIs correlated to an incident's targets
type IncidentCIsRequest struct {
	Id string `json:"-"`
}

func (c *Client) IncidentCIs(ctx context.Context, req IncidentCIsRequest) (map[string]any, error) {
	path := "/v1/incidents/{id}/cis"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List tenant-owned saved inventory views
type ListInventoryViewsRequest struct {
	Surface *string `json:"-"`
}

func (c *Client) ListInventoryViews(ctx context.Context, req ListInventoryViewsRequest) (*InventorySavedViewList, error) {
	path := "/v1/inventory/views"
	query := url.Values{}
	if req.Surface != nil {
		query.Set("surface", formatQueryValue(*req.Surface))
	}
	var out InventorySavedViewList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a tenant-owned saved inventory view
type CreateInventoryViewRequest struct {
	Body *InventorySavedViewInput `json:"-"`
}

func (c *Client) CreateInventoryView(ctx context.Context, req CreateInventoryViewRequest) (*InventorySavedView, error) {
	path := "/v1/inventory/views"
	query := url.Values{}
	var out InventorySavedView
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Open a tenant-owned saved inventory view
type GetInventoryViewRequest struct {
	Id string `json:"-"`
}

func (c *Client) GetInventoryView(ctx context.Context, req GetInventoryViewRequest) (*InventorySavedView, error) {
	path := "/v1/inventory/views/{id}"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out InventorySavedView
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get the caller tenant's effective isolation posture
type GetIsolationStatusRequest struct {
}

func (c *Client) GetIsolationStatus(ctx context.Context, req GetIsolationStatusRequest) (*IsolationStatus, error) {
	path := "/v1/isolation/status"
	query := url.Values{}
	var out IsolationStatus
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// IRREVERSIBLE verifiable erasure across every store; requires confirm=<tenant slug>; returns the deletion attestation (also appended to the provider audit chain)
type PostV1LifecycleEraseRequest struct {
}

func (c *Client) PostV1LifecycleErase(ctx context.Context, req PostV1LifecycleEraseRequest) error {
	path := "/v1/lifecycle/erase"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Download the tenant's portability bundle (tar.gz: manifest + postgres/<table>.jsonl + flows.jsonl; S-T5 — export is a compliance right, core)
type GetV1LifecycleExportRequest struct {
}

func (c *Client) GetV1LifecycleExport(ctx context.Context, req GetV1LifecycleExportRequest) error {
	path := "/v1/lifecycle/export"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// The tenant's retention policy + residency/isolation visibility
type GetV1LifecycleRetentionRequest struct {
}

func (c *Client) GetV1LifecycleRetention(ctx context.Context, req GetV1LifecycleRetentionRequest) (*LifecycleStatus, error) {
	path := "/v1/lifecycle/retention"
	query := url.Values{}
	var out LifecycleStatus
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Set the tenant's flow-retention days (null = deployment default; audited)
type PutV1LifecycleRetentionRequest struct {
	Body *LifecycleRetentionInput `json:"-"`
}

func (c *Client) PutV1LifecycleRetention(ctx context.Context, req PutV1LifecycleRetentionRequest) (*LifecycleStatus, error) {
	path := "/v1/lifecycle/retention"
	query := url.Values{}
	var out LifecycleStatus
	if err := c.doJSON(ctx, http.MethodPut, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Erase one data subject across identity, persisted AI answers, flow telemetry, OTLP telemetry, and append an audit projection marker; requires confirm equal to subject
type PostV1LifecycleSubjectsEraseRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) PostV1LifecycleSubjectsErase(ctx context.Context, req PostV1LifecycleSubjectsEraseRequest) error {
	path := "/v1/lifecycle/subjects/erase"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, req.Body, nil)
}

// Download a subject-scoped portability bundle across identity, telemetry, AI, and audit evidence; subject travels in the JSON body, never the URL
type PostV1LifecycleSubjectsExportRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) PostV1LifecycleSubjectsExport(ctx context.Context, req PostV1LifecycleSubjectsExportRequest) error {
	path := "/v1/lifecycle/subjects/export"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, req.Body, nil)
}

// The authenticated caller's tenant, identity, and effective permissions
type GetMeRequest struct {
}

func (c *Client) GetMe(ctx context.Context, req GetMeRequest) (*Me, error) {
	path := "/v1/me"
	query := url.Values{}
	var out Me
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Get on-call and ITSM integration status
type GetOncallStatusRequest struct {
}

func (c *Client) GetOncallStatus(ctx context.Context, req GetOncallStatusRequest) (*OncallStatus, error) {
	path := "/v1/oncall/status"
	query := url.Values{}
	var out OncallStatus
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Send a test incident through a configured on-call connector
type TestOncallConnectorRequest struct {
	Body *OncallTestRequest `json:"-"`
}

func (c *Client) TestOncallConnector(ctx context.Context, req TestOncallConnectorRequest) (*OncallTestResponse, error) {
	path := "/v1/oncall/test"
	query := url.Values{}
	var out OncallTestResponse
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// List OTLP bearer token metadata for the caller's tenant
type ListOtlpTokensRequest struct {
}

func (c *Client) ListOtlpTokens(ctx context.Context, req ListOtlpTokensRequest) (map[string]any, error) {
	path := "/v1/otlp-tokens"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Mint a DB-backed OTLP bearer token for the caller's tenant
type CreateOtlpTokenRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) CreateOtlpToken(ctx context.Context, req CreateOtlpTokenRequest) (map[string]any, error) {
	path := "/v1/otlp-tokens"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Revoke a DB-backed OTLP bearer token for the caller's tenant
type RevokeOtlpTokenRequest struct {
	Id string `json:"-"`
}

func (c *Client) RevokeOtlpToken(ctx context.Context, req RevokeOtlpTokenRequest) error {
	path := "/v1/otlp-tokens/{id}"
	if req.Id == "" {
		return fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// Query externally-ingested OTLP log records (tenant-scoped)
type OtlpLogsRequest struct {
	Service     *string `json:"-"`
	TraceId     *string `json:"-"`
	Since       *string `json:"-"`
	Until       *string `json:"-"`
	Limit       *int    `json:"-"`
	MinSeverity *int    `json:"-"`
}

func (c *Client) OtlpLogs(ctx context.Context, req OtlpLogsRequest) (map[string]any, error) {
	path := "/v1/otlp/logs"
	query := url.Values{}
	if req.Service != nil {
		query.Set("service", formatQueryValue(*req.Service))
	}
	if req.TraceId != nil {
		query.Set("trace_id", formatQueryValue(*req.TraceId))
	}
	if req.Since != nil {
		query.Set("since", formatQueryValue(*req.Since))
	}
	if req.Until != nil {
		query.Set("until", formatQueryValue(*req.Until))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	if req.MinSeverity != nil {
		query.Set("min_severity", formatQueryValue(*req.MinSeverity))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Query externally-ingested OTLP trace spans (tenant-scoped)
type OtlpTracesRequest struct {
	Service *string `json:"-"`
	TraceId *string `json:"-"`
	Since   *string `json:"-"`
	Until   *string `json:"-"`
	Limit   *int    `json:"-"`
}

func (c *Client) OtlpTraces(ctx context.Context, req OtlpTracesRequest) (map[string]any, error) {
	path := "/v1/otlp/traces"
	query := url.Values{}
	if req.Service != nil {
		query.Set("service", formatQueryValue(*req.Service))
	}
	if req.TraceId != nil {
		query.Set("trace_id", formatQueryValue(*req.TraceId))
	}
	if req.Since != nil {
		query.Set("since", formatQueryValue(*req.Since))
	}
	if req.Until != nil {
		query.Set("until", formatQueryValue(*req.Until))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Collective internet-outage view (S47a)
type GetOutagesRequest struct {
}

func (c *Client) GetOutages(ctx context.Context, req GetOutagesRequest) (map[string]any, error) {
	path := "/v1/outages"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Federation scrape (text exposition of latest samples)
type PromFederateRequest struct {
	Match *string `json:"-"`
}

func (c *Client) PromFederate(ctx context.Context, req PromFederateRequest) ([]byte, error) {
	path := "/v1/prometheus/federate"
	query := url.Values{}
	if req.Match != nil {
		query.Set("match[]", formatQueryValue(*req.Match))
	}
	return c.doRaw(ctx, http.MethodGet, path, query, nil)
}

// Prometheus remote-write ingest (snappy-compressed protobuf)
type PromRemoteWriteRequest struct {
}

func (c *Client) PromRemoteWrite(ctx context.Context, req PromRemoteWriteRequest) error {
	path := "/v1/prometheus/write"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// List guarded-remediation proposals (S-EE5). Hidden 404 when the remediation feature is unlicensed
type GetV1RemediationProposalsRequest struct {
}

func (c *Client) GetV1RemediationProposals(ctx context.Context, req GetV1RemediationProposalsRequest) error {
	path := "/v1/remediation/proposals"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// File a remediation PROPOSAL (a suggestion grounded in RCA/topology). Always state=proposed — probectl never executes; a human must approve
type PostV1RemediationProposalsRequest struct {
}

func (c *Client) PostV1RemediationProposals(ctx context.Context, req PostV1RemediationProposalsRequest) error {
	path := "/v1/remediation/proposals"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Get one remediation proposal + its dry-run/blast-radius
type GetV1RemediationProposalsIdRequest struct {
}

func (c *Client) GetV1RemediationProposalsId(ctx context.Context, req GetV1RemediationProposalsIdRequest) error {
	path := "/v1/remediation/proposals/{id}"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Record a human's APPROVAL (remediation.approve; advisory-only-by-default; blast-radius-limited; audited). probectl executes NOTHING — operators carry it out
type PostV1RemediationProposalsIdApproveRequest struct {
}

func (c *Client) PostV1RemediationProposalsIdApprove(ctx context.Context, req PostV1RemediationProposalsIdApproveRequest) error {
	path := "/v1/remediation/proposals/{id}/approve"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Record a human's rejection of a remediation proposal (audited)
type PostV1RemediationProposalsIdRejectRequest struct {
}

func (c *Client) PostV1RemediationProposalsIdReject(ctx context.Context, req PostV1RemediationProposalsIdRejectRequest) error {
	path := "/v1/remediation/proposals/{id}/reject"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Latest synthetic result per (type, target, agent) with full detail
type ListLatestResultsRequest struct {
}

func (c *Client) ListLatestResults(ctx context.Context, req ListLatestResultsRequest) (map[string]any, error) {
	path := "/v1/results/latest"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// List staged rollouts (OPS-002)
type ListRolloutsRequest struct {
}

func (c *Client) ListRollouts(ctx context.Context, req ListRolloutsRequest) (map[string]any, error) {
	path := "/v1/rollouts"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Plan a staged rollout over the live fleet
type CreateRolloutRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) CreateRollout(ctx context.Context, req CreateRolloutRequest) (map[string]any, error) {
	path := "/v1/rollouts"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Get a rollout's wave state + progress
type GetRolloutRequest struct {
	Id string `json:"-"`
}

func (c *Client) GetRollout(ctx context.Context, req GetRolloutRequest) (map[string]any, error) {
	path := "/v1/rollouts/{id}"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Advance a rollout
type AdvanceRolloutRequest struct {
	Id string `json:"-"`
}

func (c *Client) AdvanceRollout(ctx context.Context, req AdvanceRolloutRequest) (map[string]any, error) {
	path := "/v1/rollouts/{id}/advance"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Halt a rollout
type HaltRolloutRequest struct {
	Id   string          `json:"-"`
	Body *map[string]any `json:"-"`
}

func (c *Client) HaltRollout(ctx context.Context, req HaltRolloutRequest) (map[string]any, error) {
	path := "/v1/rollouts/{id}/halt"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Resume a rollout
type ResumeRolloutRequest struct {
	Id   string          `json:"-"`
	Body *map[string]any `json:"-"`
}

func (c *Client) ResumeRollout(ctx context.Context, req ResumeRolloutRequest) (map[string]any, error) {
	path := "/v1/rollouts/{id}/resume"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Verify the applying rollout wave from the live agent registry
type VerifyRolloutRequest struct {
	Id string `json:"-"`
}

func (c *Client) VerifyRollout(ctx context.Context, req VerifyRolloutRequest) (map[string]any, error) {
	path := "/v1/rollouts/{id}/verify"
	if req.Id == "" {
		return nil, fmt.Errorf("id is required")
	}
	path = strings.ReplaceAll(path, "{id}", url.PathEscape(req.Id))
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// RUM convergence view (S47b)
type GetRumRequest struct {
}

func (c *Client) GetRum(ctx context.Context, req GetRumRequest) (map[string]any, error) {
	path := "/v1/rum"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Secret-backend health (S41)
type GetSecretsHealthRequest struct {
}

func (c *Client) GetSecretsHealth(ctx context.Context, req GetSecretsHealthRequest) (map[string]any, error) {
	path := "/v1/secrets/health"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// The tenant's at-rest key chain (S-T6: versions, mode, state — key MATERIAL never crosses; hidden 404 when byok is not licensed)
type GetV1SecurityKeysRequest struct {
}

func (c *Client) GetV1SecurityKeys(ctx context.Context, req GetV1SecurityKeysRequest) error {
	path := "/v1/security/keys"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodGet, path, query, nil, nil)
}

// Rotate the tenant's key: managed re-key or BYOK via an S41 secret reference (validated-resolvable BEFORE activation — the lockout guard); retired versions stay decrypt-only (no downtime)
type PostV1SecurityKeysRotateRequest struct {
}

func (c *Client) PostV1SecurityKeysRotate(ctx context.Context, req PostV1SecurityKeysRotateRequest) error {
	path := "/v1/security/keys/rotate"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodPost, path, query, nil, nil)
}

// Get SIEM export status
type GetSiemStatusRequest struct {
}

func (c *Client) GetSiemStatus(ctx context.Context, req GetSiemStatusRequest) (*SIEMStatus, error) {
	path := "/v1/siem/status"
	query := url.Values{}
	var out SIEMStatus
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// SLO statuses (S45)
type ListSlOsRequest struct {
}

func (c *Client) ListSlOs(ctx context.Context, req ListSlOsRequest) (map[string]any, error) {
	path := "/v1/slos"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// OpenSLO export (S45)
type ExportOpenSloRequest struct {
}

func (c *Client) ExportOpenSlo(ctx context.Context, req ExportOpenSloRequest) ([]byte, error) {
	path := "/v1/slos/openslo"
	query := url.Values{}
	return c.doRaw(ctx, http.MethodGet, path, query, nil)
}

// List synthetic tests
type ListTestsRequest struct {
	After *string `json:"-"`
	Limit *int    `json:"-"`
}

func (c *Client) ListTests(ctx context.Context, req ListTestsRequest) (*TestList, error) {
	path := "/v1/tests"
	query := url.Values{}
	if req.After != nil {
		query.Set("after", formatQueryValue(*req.After))
	}
	if req.Limit != nil {
		query.Set("limit", formatQueryValue(*req.Limit))
	}
	var out TestList
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Create a synthetic test
type CreateTestRequest struct {
	Q     *string      `json:"-"`
	Cause *string      `json:"-"`
	Body  *TestRequest `json:"-"`
}

func (c *Client) CreateTest(ctx context.Context, req CreateTestRequest) (*Test, error) {
	path := "/v1/tests"
	query := url.Values{}
	if req.Q != nil {
		query.Set("q", formatQueryValue(*req.Q))
	}
	if req.Cause != nil {
		query.Set("cause", formatQueryValue(*req.Cause))
	}
	var out Test
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Signed, pull-able bundle of the tenant's enabled tests (ARCH-001)
type GetTestBundleRequest struct {
}

func (c *Client) GetTestBundle(ctx context.Context, req GetTestBundleRequest) (map[string]any, error) {
	path := "/v1/tests/bundle"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Get a test
type GetTestRequest struct {
}

func (c *Client) GetTest(ctx context.Context, req GetTestRequest) (*Test, error) {
	path := "/v1/tests/{id}"
	query := url.Values{}
	var out Test
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Update a test
type UpdateTestRequest struct {
	Body *TestRequest `json:"-"`
}

func (c *Client) UpdateTest(ctx context.Context, req UpdateTestRequest) (*Test, error) {
	path := "/v1/tests/{id}"
	query := url.Values{}
	var out Test
	if err := c.doJSON(ctx, http.MethodPut, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Delete a test
type DeleteTestRequest struct {
}

func (c *Client) DeleteTest(ctx context.Context, req DeleteTestRequest) error {
	path := "/v1/tests/{id}"
	query := url.Values{}
	return c.doJSON(ctx, http.MethodDelete, path, query, nil, nil)
}

// Latest discovered network path for a test (path-viz data)
type GetTestPathRequest struct {
}

func (c *Client) GetTestPath(ctx context.Context, req GetTestPathRequest) (*Path, error) {
	path := "/v1/tests/{id}/path"
	query := url.Values{}
	var out Path
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Run a path discovery for a test and return the path
type DiscoverTestPathRequest struct {
}

func (c *Client) DiscoverTestPath(ctx context.Context, req DiscoverTestPathRequest) (*Path, error) {
	path := "/v1/tests/{id}/path"
	query := url.Values{}
	var out Path
	if err := c.doJSON(ctx, http.MethodPost, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// Recent IOC/NDR detections with source attribution + confidence
type ListThreatDetectionsRequest struct {
}

func (c *Client) ListThreatDetections(ctx context.Context, req ListThreatDetectionsRequest) (map[string]any, error) {
	path := "/v1/threat/detections"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// TLS/certificate posture inventory (latest analyzed posture per target)
type ListTlsPostureRequest struct {
}

func (c *Client) ListTlsPosture(ctx context.Context, req ListTlsPostureRequest) (map[string]any, error) {
	path := "/v1/tls/posture"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Topology dependency graph (S43)
type GetTopologyRequest struct {
	At *string `json:"-"`
}

func (c *Client) GetTopology(ctx context.Context, req GetTopologyRequest) (map[string]any, error) {
	path := "/v1/topology"
	query := url.Values{}
	if req.At != nil {
		query.Set("at", formatQueryValue(*req.At))
	}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// What-if / impact simulation (S43)
type SimulateWhatIfRequest struct {
	Body *map[string]any `json:"-"`
}

func (c *Client) SimulateWhatIf(ctx context.Context, req SimulateWhatIfRequest) (map[string]any, error) {
	path := "/v1/topology/whatif"
	query := url.Values{}
	var out map[string]any
	if err := c.doJSON(ctx, http.MethodPost, path, query, req.Body, &out); err != nil {
		return nil, err
	}
	return out, nil
}

// Build metadata
type GetVersionRequest struct {
}

func (c *Client) GetVersion(ctx context.Context, req GetVersionRequest) (*Version, error) {
	path := "/version"
	query := url.Values{}
	var out Version
	if err := c.doJSON(ctx, http.MethodGet, path, query, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) doJSON(ctx context.Context, method, path string, query url.Values, body any, out any) error {
	data, err := c.doRaw(ctx, method, path, query, body)
	if err != nil {
		return err
	}
	if out == nil || len(data) == 0 {
		return nil
	}
	return json.Unmarshal(data, out)
}

func (c *Client) doRaw(ctx context.Context, method, path string, query url.Values, body any) ([]byte, error) {
	var r io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, err
		}
		r = bytes.NewReader(b)
	}
	u, err := url.Parse(c.BaseURL + path)
	if err != nil {
		return nil, err
	}
	if len(query) > 0 {
		u.RawQuery = query.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, method, u.String(), r)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.UserAgent != "" {
		req.Header.Set("User-Agent", c.UserAgent)
	}
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	if c.Tenant != "" {
		req.Header.Set("X-Probectl-Tenant", c.Tenant)
	}
	hc := c.HTTPClient
	if hc == nil {
		hc = http.DefaultClient
	}
	resp, err := hc.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(resp.Body)
	if resp.StatusCode/100 != 2 {
		return nil, decodeError(resp.StatusCode, data)
	}
	return data, nil
}

func decodeError(status int, body []byte) error {
	var env struct {
		Error struct {
			Code    string `json:"code"`
			Message string `json:"message"`
		} `json:"error"`
	}
	_ = json.Unmarshal(body, &env)
	return &SDKError{StatusCode: status, Code: env.Error.Code, Message: env.Error.Message, Body: body}
}

func formatQueryValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case int:
		return strconv.Itoa(x)
	case bool:
		return strconv.FormatBool(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	default:
		return fmt.Sprint(x)
	}
}
