#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-probectl-TBD
#
# export-receipts.sh — TEST-011 (receipts half) / data-room receipts bundle.
#
# Exports the evidence that the merge gates and protections are real, into a
# single dated bundle for the data room: the branch-protection ruleset, the
# latest green verify-all summary, and the coverage report. It reads from GitHub
# (needs `gh` authenticated) — it does not invent receipts; it captures the
# actual current state.
#
#   REPO=owner/probectl ./scripts/export-receipts.sh
set -euo pipefail

die() {
  echo "export-receipts: $*" >&2
  exit 1
}

download_required_artifact() {
  local run_id="$1"
  local name="$2"
  local out="$3"
  gh run download "$run_id" --repo "$REPO" --name "$name" --dir "$out" ||
    die "required artifact ${name} was not downloadable from run ${run_id}"
}

require_file() {
  local path="$1"
  [ -s "$path" ] || die "required receipt file is missing or empty: ${path}"
}

validate_branch_protection() {
  local path="$1"
  python3 - "$path" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, encoding="utf-8") as f:
    data = json.load(f)

required = {"verify-all", "commitlint", "dco"}
checks = set(data.get("required_status_checks", {}).get("contexts") or [])
for check in data.get("required_status_checks", {}).get("checks") or []:
    ctx = check.get("context") or check.get("name")
    if ctx:
        checks.add(ctx)
missing = sorted(required - checks)
if missing:
    raise SystemExit("branch protection must require: " + ", ".join(missing))

enforce_admins = data.get("enforce_admins")
if isinstance(enforce_admins, dict):
    admins_included = bool(enforce_admins.get("enabled"))
else:
    admins_included = bool(enforce_admins)
if not admins_included:
    raise SystemExit("branch protection must include admins / disallow bypass")
PY
}

export_receipts() {
  REPO="${REPO:-imfeelingtheagi/probectl}"
  OUT="${OUT:-dataroom-receipts-$(date -u +%Y%m%d)}"
  mkdir -p "$OUT"

  echo "exporting receipts for $REPO -> $OUT/" >&2

  # 1. Branch protection ruleset (TEST-001 receipt): proves required checks,
  #    require-PR, include-admins are actually enforced on main.
  gh api "repos/${REPO}/branches/main/protection" > "$OUT/branch-protection.json"
  require_file "$OUT/branch-protection.json"
  validate_branch_protection "$OUT/branch-protection.json"

  # 2. Latest green ci.yml run on main. A missing successful run is a missing
  #    receipt, not a warning: the data room must never look green by omission.
  run_id="$(gh run list --repo "$REPO" --workflow ci.yml --branch main \
    --status success --limit 1 --json databaseId --jq '.[0].databaseId')"
  [ -n "${run_id:-}" ] || die "no successful ci.yml run found on main"

  # 3. Required receipts from that run. These names mirror ci.yml upload-artifact
  #    declarations; do not silently skip them.
  download_required_artifact "$run_id" verify-all-receipt "$OUT"
  require_file "$OUT/verify-all-summary.json"

  download_required_artifact "$run_id" coverage-receipt "$OUT"
  require_file "$OUT/coverage.out"
  require_file "$OUT/coverage-summary.txt"

  cat > "$OUT/README.md" <<EOF
# Data-room receipts bundle ($(date -u +%Y-%m-%d))

- branch-protection.json — the enforced ruleset on main (required checks,
  require-PR, include-admins) — TEST-001.
- verify-all-summary.json — the per-gate green/red receipt from the latest
  successful ci run on main — TEST-006/009.
- coverage.out and coverage-summary.txt — the declared-floor coverage report —
  TEST-003/004.

Generated by scripts/export-receipts.sh against ${REPO}.
EOF

  echo "done: $OUT/" >&2
}

selftest() {
  local tmp bin log
  tmp="$(mktemp -d)"
  bin="$tmp/bin"
  log="$tmp/gh.log"
  mkdir -p "$bin"
  SELFTEST_TMP="$tmp"
  trap 'rm -rf "$SELFTEST_TMP"' EXIT

  cat > "$bin/gh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "${GH_LOG:?}"
if [ "$1" = "api" ]; then
  if [ "${GH_BAD_BRANCH_PROTECTION:-}" = "1" ]; then
    printf '{"required_status_checks":{"checks":[{"context":"unit"}]},"enforce_admins":{"enabled":false}}\n'
  else
    printf '{"required_status_checks":{"checks":[{"context":"verify-all"},{"context":"commitlint"},{"context":"dco"}]},"enforce_admins":{"enabled":true}}\n'
  fi
  exit 0
fi
if [ "$1" = "run" ] && [ "$2" = "list" ]; then
  printf '123456\n'
  exit 0
fi
if [ "$1" = "run" ] && [ "$2" = "download" ]; then
  name=""
  dir=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --name)
        name="$2"
        shift 2
        ;;
      --dir)
        dir="$2"
        shift 2
        ;;
      *)
        shift
        ;;
    esac
  done
  [ -n "$name" ] && [ -n "$dir" ] || exit 64
  if [ "${GH_FAIL_ARTIFACT:-}" = "$name" ]; then
    exit 42
  fi
  case "$name" in
    verify-all-receipt)
      printf '{"state":"green"}\n' > "$dir/verify-all-summary.json"
      ;;
    coverage-receipt)
      printf 'mode: set\n' > "$dir/coverage.out"
      printf 'total: 80.0%%\n' > "$dir/coverage-summary.txt"
      ;;
    *)
      exit 65
      ;;
  esac
  exit 0
fi
exit 66
EOF
  chmod +x "$bin/gh"

  GH_LOG="$log" PATH="$bin:$PATH" REPO=example/probectl OUT="$tmp/out" SELFTEST= "$0" >/dev/null
  require_file "$tmp/out/branch-protection.json"
  require_file "$tmp/out/verify-all-summary.json"
  require_file "$tmp/out/coverage.out"
  require_file "$tmp/out/coverage-summary.txt"
  grep -q -- "--name coverage-receipt" "$log" ||
    die "selftest did not request coverage-receipt"
  if grep -q -- "--name coverage --" "$log"; then
    die "selftest saw stale coverage artifact name"
  fi

  if GH_LOG="$tmp/fail.log" PATH="$bin:$PATH" REPO=example/probectl OUT="$tmp/fail" \
    GH_FAIL_ARTIFACT=coverage-receipt SELFTEST= "$0" >/dev/null 2>&1; then
    die "selftest expected missing coverage-receipt download to fail"
  fi
  if GH_LOG="$tmp/branch-fail.log" PATH="$bin:$PATH" REPO=example/probectl OUT="$tmp/branch-fail" \
    GH_BAD_BRANCH_PROTECTION=1 SELFTEST= "$0" >/dev/null 2>&1; then
    die "selftest expected invalid branch protection to fail"
  fi
  echo "export-receipts selftest: OK" >&2
}

if [ "${SELFTEST:-}" = "1" ]; then
  selftest
else
  export_receipts
fi
