#!/usr/bin/env bash
# SPDX-License-Identifier: LicenseRef-probectl-TBD
#
# export-receipts.sh — TEST-011 (receipts half) / data-room receipts bundle.
#
# Exports the evidence that the merge gates and protections are real, into a
# single dated bundle for the data room: the branch-protection ruleset, the
# latest green verify-all summary, and the coverage report. It reads from GitHub
# (needs `gh` authenticated) — it does not invent receipts; it captures the
# actual current state.
#
#   REPO=owner/probectl ./scripts/export-receipts.sh
set -euo pipefail

REPO="${REPO:-imfeelingtheagi/probectl}"
OUT="${OUT:-dataroom-receipts-$(date -u +%Y%m%d)}"
mkdir -p "$OUT"

echo "exporting receipts for $REPO -> $OUT/" >&2

# 1. Branch protection ruleset (TEST-001 receipt): proves required checks,
#    require-PR, include-admins are actually enforced on main.
gh api "repos/${REPO}/branches/main/protection" > "$OUT/branch-protection.json"

# 2. Latest verify-all receipt artifact from the most recent green run on main.
run_id="$(gh run list --repo "$REPO" --workflow ci.yml --branch main \
  --status success --limit 1 --json databaseId --jq '.[0].databaseId')"
if [ -n "${run_id:-}" ]; then
  gh run download "$run_id" --repo "$REPO" --name verify-all-receipt --dir "$OUT" || true
fi

# 3. Coverage receipt, if published as an artifact.
if [ -n "${run_id:-}" ]; then
  gh run download "$run_id" --repo "$REPO" --name coverage --dir "$OUT" || true
fi

cat > "$OUT/README.md" <<EOF
# Data-room receipts bundle ($(date -u +%Y-%m-%d))

- branch-protection.json — the enforced ruleset on main (required checks,
  require-PR, include-admins) — TEST-001.
- verify-all-summary.json — the per-gate green/red receipt from the latest
  successful ci run on main — TEST-006/009.
- coverage* — the declared-floor coverage report — TEST-003/004.

Generated by scripts/export-receipts.sh against ${REPO}.
EOF

echo "done: $OUT/" >&2
