#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
#
# release_notes.sh [FROM] [TO] — exhaustive, conventional-commit-grouped notes.
# FROM defaults to the latest tag, TO to HEAD. Every non-merge commit is emitted
# exactly once: recognized Conventional Commit types get a named section and
# everything else remains visible under "Other changes".
#
#   scripts/release_notes.sh v0.5.0 HEAD
#   scripts/release_notes.sh                # latest tag → HEAD (the next section)
set -euo pipefail

FROM="${1:-$(git describe --tags --abbrev=0)}"
TO="${2:-HEAD}"

git rev-parse --verify "${FROM}^{commit}" >/dev/null
git rev-parse --verify "${TO}^{commit}" >/dev/null

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
buckets="features fixes performance security_ci tests documentation maintenance other"
for bucket in $buckets; do
  : > "$tmp/$bucket"
done

git log --no-merges --format='%H%x09%s' "${FROM}..${TO}" > "$tmp/commits"
conventional_re='^([a-z]+)(\([^)]*\))?(!)?:[[:space:]]+'
total=0
while IFS=$'\t' read -r _commit subject; do
  [ -n "${_commit:-}" ] || continue
  bucket="other"
  if [[ "$subject" =~ $conventional_re ]]; then
    case "${BASH_REMATCH[1]}" in
      feat) bucket="features" ;;
      fix) bucket="fixes" ;;
      perf) bucket="performance" ;;
      ci|build) bucket="security_ci" ;;
      test) bucket="tests" ;;
      docs) bucket="documentation" ;;
      chore|style|refactor) bucket="maintenance" ;;
    esac
  fi
  printf -- '- %s\n' "$subject" >> "$tmp/$bucket"
  total=$((total + 1))
done < "$tmp/commits"

accounted=0
for bucket in $buckets; do
  count="$(wc -l < "$tmp/$bucket" | tr -d '[:space:]')"
  accounted=$((accounted + count))
done
if [ "$accounted" -ne "$total" ]; then
  echo "release notes: internal accounting error: ${accounted}/${total} commits assigned" >&2
  exit 1
fi

section() {
  local title="$1" bucket="$2"
  [ -s "$tmp/$bucket" ] || return 0
  printf '### %s\n\n' "$title"
  cat "$tmp/$bucket"
  printf '\n'
}

echo "<!-- generated by scripts/release_notes.sh ${FROM}..${TO}; ${total} non-merge commits -->"
section "Features" "features"
section "Fixes" "fixes"
section "Performance" "performance"
section "Security & CI" "security_ci"
section "Tests" "tests"
section "Documentation" "documentation"
section "Maintenance" "maintenance"
section "Other changes" "other"
