#!/usr/bin/env bash
# SPDX-License-Identifier: BUSL-1.1
#
# Run an npm command for web/ inside the SAME digest-pinned Node image CI and
# deploy/docker/Dockerfile use, instead of whatever npm the host happens to have.
#
# DPR-236: web/package-lock.json is owned by ONE npm version, and it is not the
# laptop's. npm 10 and npm 11 disagree about lockfile content in a way that makes
# a lock written by one unusable by the other:
#
#   * npm 11 records every platform-specific optional binary (72 @esbuild/* and
#     @rollup/* nodes) and writes them WITHOUT "optional": true. npm 10 then tries
#     to install @esbuild/netbsd-arm64 on linux/x64 and dies with EBADPLATFORM.
#   * npm 10 omits those nodes entirely. npm 11 then refuses the lock with EUSAGE,
#     "Missing: @esbuild/aix-ppc64@0.21.5 from lock file", 72 times.
#
# Every consumer in CI is npm 10: the Dockerfile's digest-pinned node:22 stage
# (8 build-images jobs + image-scan), the three setup-node jobs at node-version
# "22", and web-rendered-a11y inside the Playwright container. So npm 10 owns the
# lock, and the way to produce or check it is this script — not `npm` on a host.
#
#   scripts/web_npm.sh ci                 # install exactly what the lock says
#   scripts/web_npm.sh install --package-lock-only   # regenerate the lock
#   scripts/web_npm.sh run typecheck
#
# internal/cipolicy TestWebLockHasNoNonOptionalPlatformBinaries fails if a lock
# generated by the wrong npm is ever committed.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# The digest below is kept byte-identical to deploy/docker/Dockerfile's web stage —
# the image that builds the shipped bundle is the image that owns the lock — and it
# is a LITERAL because SUPPLY-002 requires a statically identifiable digest.
# internal/cipolicy TestWebNodeImageMatchesTheDockerfile fails if they drift.
PLATFORM="${PROBECTL_WEB_NODE_PLATFORM:-linux/amd64}"

if [ "$#" -eq 0 ]; then
  echo "usage: scripts/web_npm.sh <npm args...>" >&2
  exit 2
fi

exec docker run --rm \
  --platform "$PLATFORM" \
  -v "$repo_root:/src" \
  -w /src/web \
  -e npm_config_update_notifier=false \
  -e HOME=/tmp \
  node:22-bookworm-slim@sha256:e21fc383b50d5347dc7a9f1cae45b8f4e2f0d39f7ade28e4eef7d2934522b752 \
  npm "$@"
