// SPDX-License-Identifier: MPL-2.0
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, test } from 'vitest'
import {
  JourneyRecorder,
  assertRequestsUseSessionTenant,
  buildBaselineArtifact,
  comparableActiveTimeMs,
  validateJourneyArtifact,
  type JourneyArtifact,
} from './measurement'

describe('UX journey measurement contract', () => {
  test('the versioned artifact is generated by the deterministic J1-J6 fixtures', () => {
    const committed = JSON.parse(
      readFileSync(resolve(process.cwd(), '../docs/ux/journey-baseline.json'), 'utf8'),
    ) as JourneyArtifact
    const generated = buildBaselineArtifact()

    validateJourneyArtifact(committed)
    expect(committed).toEqual(generated)
    expect(committed.measurements.map((row) => row.journey)).toEqual([
      'J1',
      'J2',
      'J3',
      'J4',
      'J5',
      'J6',
    ])
  })

  test('a fast incomplete path has no comparable elapsed time', () => {
    const partial = new JourneyRecorder('J2', 'partial incident path')
      .pointer()
      .activeTimeProxy({ min_ms: 1, max_ms: 2, basis: 'deterministic test clock' })
      .incomplete('share is missing')
      .snapshot()

    expect(comparableActiveTimeMs(partial)).toBeNull()
    expect(() =>
      new JourneyRecorder('J2', 'false complete')
        .activeTimeProxy({ min_ms: 1, max_ms: 2, basis: 'deterministic test clock' })
        .complete(),
    ).toThrow(/requires outcome evidence/)
  })

  test('fixture requests derive tenant from the session and reject spoofing channels', () => {
    expect(() =>
      assertRequestsUseSessionTenant([
        { url: '/v1/incidents?from=2026-07-14T00%3A00%3A00Z' },
        { url: '/v1/ai/ask', method: 'POST', body: { subject: { incident_id: 'inc-1' } } },
      ]),
    ).not.toThrow()

    for (const request of [
      { url: '/v1/incidents?tenant_id=tenant-b' },
      { url: '/v1/ai/ask', method: 'POST', body: { subject: { tenant_id: 'tenant-b' } } },
      { url: '/v1/agents', headers: { 'X-Probectl-Tenant': 'tenant-b' } },
    ]) {
      expect(() => assertRequestsUseSessionTenant([request])).toThrow(/supplies tenant/i)
    }
  })

  test('the artifact validator rejects duplicates and invalid counters', () => {
    const duplicate = buildBaselineArtifact()
    duplicate.measurements[1] = { ...duplicate.measurements[0] }
    expect(() => validateJourneyArtifact(duplicate)).toThrow(/duplicate J1/)

    const invalid = buildBaselineArtifact()
    invalid.measurements[0] = { ...invalid.measurements[0], pointer_interactions: -1 }
    expect(() => validateJourneyArtifact(invalid)).toThrow(/non-negative integer/)
  })
})
